# Generated by Django 5.2.14 on 2026-08-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubs",
                to="sports.competition",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubs",
                to="sports.sport",
            ),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                fields=["sport", "is_active"], name="profiles_cl_sport_i_1b0711_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="club",
            index=models.Index(
                fields=["competition", "is_active"], name="profiles_cl_competi_c17587_idx"
            ),
        ),
    ]
