# Generated by Django 5.2.17 on 2026-08-17 00:31

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_club_competition_club_sport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=profiles.models.club_logo_upload_to
            ),
        ),
    ]
