# Generated by Django 5.2.16 on 2026-07-31 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MarketTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("EVENT", "Sporting event"),
                            ("COMPETITION", "Competition"),
                            ("PARTICIPANT", "Participant"),
                            ("CUSTOM", "Custom proposition"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=180)),
                ("question_template", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("rules_template", models.TextField(blank=True)),
                ("default_yes_label", models.CharField(default="Yes", max_length=120)),
                ("default_no_label", models.CharField(default="No", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="markets.marketcategory",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_templates",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "ordering": ["category__display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("EVENT", "Sporting event"),
                            ("COMPETITION", "Competition"),
                            ("PARTICIPANT", "Participant"),
                            ("CUSTOM", "Custom proposition"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("custom_subject", models.CharField(blank=True, max_length=255)),
                ("question", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("rules", models.TextField(blank=True)),
                ("resolution_source", models.CharField(blank=True, max_length=255)),
                ("resolution_criteria", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("OPEN", "Open"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                            ("RESOLVED", "Resolved"),
                            ("VOIDED", "Voided"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("opens_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_markets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="sports.competition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_markets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="sports.participant",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_markets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="sports.sport",
                    ),
                ),
                (
                    "sporting_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="sports.sportingevent",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="markets.marketcategory",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="markets.markettemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "closes_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("side", models.CharField(choices=[("YES", "Yes"), ("NO", "No")], max_length=10)),
                ("position", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["market", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("market", "side"), name="unique_market_outcome_side"
                    ),
                    models.UniqueConstraint(
                        fields=("market", "position"), name="unique_market_outcome_position"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("position__in", [1, 2])),
                        name="market_outcome_position_is_binary",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("side", "YES"), ("position", 1)),
                            models.Q(("side", "NO"), ("position", 2)),
                            _connector="OR",
                        ),
                        name="market_outcome_side_matches_position",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="markettemplate",
            index=models.Index(
                fields=["scope_type", "is_active"], name="markets_mar_scope_t_3a2176_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="markettemplate",
            index=models.Index(
                fields=["sport", "is_active"], name="markets_mar_sport_i_b871a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["status", "closes_at"], name="markets_mar_status_226749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(fields=["sport", "status"], name="markets_mar_sport_i_cfe186_idx"),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["category", "status"], name="markets_mar_categor_1919dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["scope_type", "status"], name="markets_mar_scope_t_90e5e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["is_featured", "status"], name="markets_mar_is_feat_efa52b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("scope_type", "EVENT"),
                        ("sporting_event__isnull", False),
                        ("competition__isnull", True),
                        ("participant__isnull", True),
                        ("custom_subject", ""),
                    ),
                    models.Q(
                        ("scope_type", "COMPETITION"),
                        ("sporting_event__isnull", True),
                        ("competition__isnull", False),
                        ("participant__isnull", True),
                        ("custom_subject", ""),
                    ),
                    models.Q(
                        ("scope_type", "PARTICIPANT"),
                        ("participant__isnull", False),
                        ("custom_subject", ""),
                    ),
                    models.Q(
                        ("scope_type", "CUSTOM"),
                        ("sporting_event__isnull", True),
                        ("competition__isnull", True),
                        ("participant__isnull", True),
                        models.Q(("custom_subject", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="market_scope_target_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("opens_at__isnull", True),
                    ("closes_at__isnull", True),
                    ("closes_at__gt", models.F("opens_at")),
                    _connector="OR",
                ),
                name="market_closes_after_opening",
            ),
        ),
    ]
