# Generated by Django 5.2.16 on 2026-07-31 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketStatusTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUBMIT", "Submit for approval"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("OPEN", "Open"),
                            ("SUSPEND", "Suspend"),
                            ("REOPEN", "Reopen"),
                            ("CLOSE", "Close"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("OPEN", "Open"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                            ("RESOLVED", "Resolved"),
                            ("VOIDED", "Voided"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("OPEN", "Open"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                            ("RESOLVED", "Resolved"),
                            ("VOIDED", "Voided"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("actor_email", models.EmailField(max_length=254)),
                ("notes", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_status_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_transitions",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["market", "created_at"], name="markets_mar_market__a0b949_idx"
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="markets_mar_action_d23517_idx"
                    ),
                ],
            },
        ),
    ]
