# Generated by Django 5.2.16 on 2026-07-31 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_marketstatustransition"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="resolution_evidence",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="market",
            name="winning_outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="winning_markets",
                to="markets.marketoutcome",
            ),
        ),
        migrations.AddField(
            model_name="marketstatustransition",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="marketstatustransition",
            name="action",
            field=models.CharField(
                choices=[
                    ("SUBMIT", "Submit for approval"),
                    ("APPROVE", "Approve"),
                    ("REJECT", "Reject"),
                    ("OPEN", "Open"),
                    ("SUSPEND", "Suspend"),
                    ("REOPEN", "Reopen"),
                    ("CLOSE", "Close"),
                    ("RESOLVE", "Resolve"),
                    ("VOID", "Void"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
