# Generated by Django 5.2.16 on 2026-07-31 19:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0003_market_resolution_evidence_market_winning_outcome_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        db_index=True,
                        default="BUY",
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("limit_price", models.DecimalField(decimal_places=5, max_digits=6)),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=18),
                ),
                (
                    "average_fill_price",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OPEN", "Open"),
                            ("PARTIALLY_FILLED", "Partially filled"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="markets.market",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="markets.marketoutcome",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "created_at"],
                        name="markets_mar_user_id_356bed_idx",
                    ),
                    models.Index(
                        fields=["market", "status", "created_at"],
                        name="markets_mar_market__f72464_idx",
                    ),
                    models.Index(
                        fields=["outcome", "side", "status", "limit_price"],
                        name="markets_mar_outcome_0e5945_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="market_order_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("limit_price__gt", 0), ("limit_price__lt", 1)),
                        name="market_order_limit_price_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("filled_quantity__gte", 0)),
                        name="market_order_filled_quantity_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("filled_quantity__lte", models.F("quantity"))),
                        name="market_order_filled_quantity_within_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("average_fill_price__isnull", True),
                            models.Q(("average_fill_price__gt", 0), ("average_fill_price__lt", 1)),
                            _connector="OR",
                        ),
                        name="market_order_average_fill_price_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=18),
                ),
                (
                    "average_entry_price",
                    models.DecimalField(decimal_places=5, default=Decimal("0"), max_digits=6),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="markets.market",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="markets.marketoutcome",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "market"], name="markets_mar_user_id_6c63b5_idx"),
                    models.Index(
                        fields=["market", "outcome"], name="markets_mar_market__72961f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "market", "outcome"),
                        name="unique_user_market_outcome_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 0)),
                        name="market_position_quantity_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_cost__gte", 0)),
                        name="market_position_total_cost_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("average_entry_price__gte", 0), ("average_entry_price__lt", 1)
                        ),
                        name="market_position_average_entry_price_valid",
                    ),
                ],
            },
        ),
    ]
