# Generated by Django 5.2.16 on 2026-08-02 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0004_marketorder_marketposition"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketFill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("execution_reference", models.UUIDField(editable=False, unique=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("price", models.DecimalField(decimal_places=5, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buy_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buy_fills",
                        to="markets.marketorder",
                    ),
                ),
                (
                    "maker_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maker_fills",
                        to="markets.marketorder",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fills",
                        to="markets.market",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fills",
                        to="markets.marketoutcome",
                    ),
                ),
                (
                    "sell_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sell_fills",
                        to="markets.marketorder",
                    ),
                ),
                (
                    "taker_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="taker_fills",
                        to="markets.marketorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["market", "created_at"], name="markets_mar_market__aba8bd_idx"
                    ),
                    models.Index(
                        fields=["outcome", "created_at"], name="markets_mar_outcome_befd15_idx"
                    ),
                    models.Index(
                        fields=["buy_order", "created_at"], name="markets_mar_buy_ord_8c9154_idx"
                    ),
                    models.Index(
                        fields=["sell_order", "created_at"], name="markets_mar_sell_or_308cc2_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="market_fill_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price__gt", 0)), name="market_fill_price_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price__lt", 1)), name="market_fill_price_below_one"
                    ),
                ],
            },
        ),
    ]
