# Generated by Django 5.2.16 on 2026-08-02 19:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0005_add_market_fill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="marketposition",
            name="reserved_quantity",
            field=models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
        ),
        migrations.AddConstraint(
            model_name="marketposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", 0)),
                name="market_position_reserved_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__lte", models.F("quantity"))),
                name="market_position_reserved_quantity_within_position",
            ),
        ),
    ]
