# Generated by Django 5.2.16 on 2026-08-02 21:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0006_add_market_position_reservations"),
        ("wallets", "0001_wallet_ledger_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payout_per_unit", models.DecimalField(decimal_places=4, max_digits=20)),
                ("settlement_currency", models.CharField(max_length=3)),
                ("total_position_count", models.PositiveIntegerField(default=0)),
                ("winning_position_count", models.PositiveIntegerField(default=0)),
                ("losing_position_count", models.PositiveIntegerField(default=0)),
                (
                    "total_winning_quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                (
                    "total_payout_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executed_market_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement",
                        to="markets.market",
                    ),
                ),
                (
                    "winning_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_settlements",
                        to="markets.marketoutcome",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketPositionSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("was_winner", models.BooleanField(db_index=True)),
                ("settled_quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("payout_per_unit", models.DecimalField(decimal_places=4, max_digits=20)),
                ("payout_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("cost_basis", models.DecimalField(decimal_places=4, max_digits=20)),
                ("realized_pnl_delta", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "market_position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_record",
                        to="markets.marketposition",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_settlements",
                        to="markets.marketoutcome",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_position_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_ledger_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_position_settlement",
                        to="wallets.ledgerentry",
                    ),
                ),
                (
                    "market_settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_settlements",
                        to="markets.marketsettlement",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="marketsettlement",
            index=models.Index(fields=["executed_at"], name="markets_mar_execute_3b3617_idx"),
        ),
        migrations.AddIndex(
            model_name="marketsettlement",
            index=models.Index(
                fields=["winning_outcome", "executed_at"], name="markets_mar_winning_478ca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketpositionsettlement",
            index=models.Index(
                fields=["market_settlement", "was_winner"], name="markets_mar_market__e8ba81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketpositionsettlement",
            index=models.Index(
                fields=["participant", "created_at"], name="markets_mar_partici_cff1b2_idx"
            ),
        ),
    ]
