# Generated by Django 5.2.16 on 2026-08-03 06:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0007_marketsettlement_marketpositionsettlement_and_more"),
        ("wallets", "0001_wallet_ledger_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketVoidRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("refund_currency", models.CharField(max_length=3)),
                ("total_cancelled_order_count", models.PositiveIntegerField(default=0)),
                ("cancelled_buy_order_count", models.PositiveIntegerField(default=0)),
                ("cancelled_sell_order_count", models.PositiveIntegerField(default=0)),
                (
                    "total_released_buy_reservation_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                (
                    "total_released_sell_reservation_quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                ("refunded_position_count", models.PositiveIntegerField(default=0)),
                (
                    "total_refunded_position_quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                (
                    "total_position_refund_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executed_market_void_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="void_refund",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketVoidOrderCancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_side",
                    models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10),
                ),
                (
                    "remaining_quantity_cancelled",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "released_wallet_reservation_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                (
                    "released_position_reservation_quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                (
                    "market_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="void_cancellation_record",
                        to="markets.marketorder",
                    ),
                ),
                (
                    "wallet_release_ledger_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_void_order_cancellation",
                        to="wallets.ledgerentry",
                    ),
                ),
                (
                    "market_void_refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_cancellations",
                        to="markets.marketvoidrefund",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="MarketPositionVoidRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("refunded_quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("cost_basis", models.DecimalField(decimal_places=4, max_digits=20)),
                ("refund_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "realized_pnl_delta",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                (
                    "market_position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="void_refund_record",
                        to="markets.marketposition",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_void_refunds",
                        to="markets.marketoutcome",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_position_void_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_credit_ledger_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_position_void_refund",
                        to="wallets.ledgerentry",
                    ),
                ),
                (
                    "market_void_refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_refunds",
                        to="markets.marketvoidrefund",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="marketvoidrefund",
            index=models.Index(fields=["executed_at"], name="markets_mar_execute_759aa0_idx"),
        ),
        migrations.AddIndex(
            model_name="marketvoidordercancellation",
            index=models.Index(
                fields=["market_void_refund", "order_side"], name="markets_mar_market__643975_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketpositionvoidrefund",
            index=models.Index(
                fields=["market_void_refund", "outcome"], name="markets_mar_market__f204be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketpositionvoidrefund",
            index=models.Index(
                fields=["participant", "created_at"], name="markets_mar_partici_5fb9ab_idx"
            ),
        ),
    ]
