# Generated by Django 5.2.16 on 2026-08-03 06:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0008_add_market_void_refund_audits"),
        ("wallets", "0001_wallet_ledger_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketCloseCleanup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_cancelled_order_count", models.PositiveIntegerField(default=0)),
                ("cancelled_buy_order_count", models.PositiveIntegerField(default=0)),
                ("cancelled_sell_order_count", models.PositiveIntegerField(default=0)),
                (
                    "total_released_buy_reservation_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                (
                    "total_released_sell_reservation_quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executed_market_close_cleanups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="close_cleanup",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketCloseOrderCancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_side",
                    models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10),
                ),
                (
                    "remaining_quantity_cancelled",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "released_wallet_reservation_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                (
                    "released_position_reservation_quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                (
                    "market_close_cleanup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_cancellations",
                        to="markets.marketclosecleanup",
                    ),
                ),
                (
                    "market_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="close_cancellation_record",
                        to="markets.marketorder",
                    ),
                ),
                (
                    "wallet_release_ledger_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_close_order_cancellation",
                        to="wallets.ledgerentry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="marketclosecleanup",
            index=models.Index(fields=["executed_at"], name="markets_mar_execute_a68fbc_idx"),
        ),
        migrations.AddIndex(
            model_name="marketcloseordercancellation",
            index=models.Index(
                fields=["market_close_cleanup", "order_side"], name="markets_mar_market__eea71d_idx"
            ),
        ),
    ]
