# Generated by Django 5.2.16 on 2026-08-03 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0009_add_market_close_cleanup_audits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketParticipantCompliance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "restriction_status",
                    models.CharField(
                        choices=[
                            ("CLEAR", "Clear"),
                            ("RESTRICTED", "Restricted"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="CLEAR",
                        max_length=20,
                    ),
                ),
                (
                    "jurisdiction_override",
                    models.CharField(
                        choices=[("NONE", "None"), ("ALLOW", "Allow"), ("BLOCK", "Block")],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("jurisdiction_override_reason", models.TextField(blank=True)),
                ("internal_review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_compliance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_compliance_reviews_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketComplianceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_kyc_status", models.CharField(max_length=20)),
                ("new_kyc_status", models.CharField(max_length=20)),
                ("previous_restriction_status", models.CharField(max_length=20)),
                ("new_restriction_status", models.CharField(max_length=20)),
                ("previous_jurisdiction_override", models.CharField(max_length=10)),
                ("new_jurisdiction_override", models.CharField(max_length=10)),
                ("reason", models.TextField(blank=True)),
                ("notes_snapshot", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_compliance_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_compliance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["participant", "-created_at"], name="markets_mar_partici_b67145_idx"
                    )
                ],
            },
        ),
    ]
