# Generated by Django 5.2.16 on 2026-08-03 13:42

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0010_marketparticipantcompliance_marketcompliancereview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketResponsibleParticipation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_order_notional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "daily_buy_notional_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "weekly_buy_notional_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_open_buy_commitment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_market_exposure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_total_exposure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_cumulative_realized_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("cooling_off_until", models.DateTimeField(blank=True, null=True)),
                ("self_exclusion_until", models.DateTimeField(blank=True, null=True)),
                ("self_excluded_indefinitely", models.BooleanField(default=False)),
                ("administrative_block_until", models.DateTimeField(blank=True, null=True)),
                ("administrative_block_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_responsible_participation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_responsible_reviews_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketResponsibleParticipationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LIMITS_SET", "Limits set"),
                            ("LIMITS_TIGHTENED", "Limits tightened"),
                            ("ADMIN_LIMITS_UPDATED", "Admin limits updated"),
                            ("ADMIN_CONTROLS_UPDATED", "Admin controls updated"),
                            ("COOLING_OFF_STARTED", "Cooling off started"),
                            ("COOLING_OFF_EXTENDED", "Cooling off extended"),
                            ("SELF_EXCLUSION_STARTED", "Self exclusion started"),
                            ("SELF_EXCLUSION_EXTENDED", "Self exclusion extended"),
                            ("ADMIN_BLOCK_STARTED", "Admin block started"),
                            ("ADMIN_BLOCK_EXTENDED", "Admin block extended"),
                        ],
                        max_length=40,
                    ),
                ),
                ("previous_state", models.JSONField(default=dict)),
                ("new_state", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_responsible_participation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_responsible_participation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["participant", "-created_at", "-id"],
                        name="markets_mar_partici_8fff73_idx",
                    )
                ],
            },
        ),
    ]
