# Generated by Django 5.2.16 on 2026-08-03 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0011_marketresponsibleparticipation_and_more"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketEventGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SPORTING_EVENT", "Sporting event"),
                            ("LEAGUE_EVENT", "League event"),
                            ("GENERAL_EVENT", "General event"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_groups",
                        to="markets.marketcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_market_event_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_market_event_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sporting_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_event_groups",
                        to="sports.sportingevent",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at", "title", "id"],
            },
        ),
        migrations.AddField(
            model_name="market",
            name="event_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="markets",
                to="markets.marketeventgroup",
            ),
        ),
        migrations.CreateModel(
            name="MarketProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("EVENT", "Sporting event"),
                            ("COMPETITION", "Competition"),
                            ("PARTICIPANT", "Participant"),
                            ("CUSTOM", "Custom proposition"),
                        ],
                        default="EVENT",
                        max_length=20,
                    ),
                ),
                ("proposed_event_title", models.CharField(blank=True, max_length=255)),
                ("proposed_closes_at", models.DateTimeField(blank=True, null=True)),
                ("proposed_resolution_source", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DUPLICATE", "Duplicate"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "duplicate_status",
                    models.CharField(
                        choices=[
                            ("CLEAR", "Clear"),
                            ("POSSIBLE_DUPLICATE", "Possible duplicate"),
                            ("CONFIRMED_DUPLICATE", "Confirmed duplicate"),
                        ],
                        db_index=True,
                        default="CLEAR",
                        max_length=30,
                    ),
                ),
                (
                    "duplicate_fingerprint",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_market",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_proposal",
                        to="markets.market",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="markets.marketcategory",
                    ),
                ),
                (
                    "duplicate_of_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicate_proposals",
                        to="markets.market",
                    ),
                ),
                (
                    "duplicate_of_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicates",
                        to="markets.marketproposal",
                    ),
                ),
                (
                    "proposed_event_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="markets.marketeventgroup",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_market_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sporting_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_proposals",
                        to="sports.sportingevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketProposalReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("START_REVIEW", "Start review"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("MARK_DUPLICATE", "Mark duplicate"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DUPLICATE", "Duplicate"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DUPLICATE", "Duplicate"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_proposal_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_reviews",
                        to="markets.market",
                    ),
                ),
                (
                    "duplicate_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_reviews",
                        to="markets.market",
                    ),
                ),
                (
                    "duplicate_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicate_review_references",
                        to="markets.marketproposal",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="markets.marketproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="marketeventgroup",
            index=models.Index(
                fields=["status", "scheduled_at"], name="markets_mar_status_86be5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketeventgroup",
            index=models.Index(
                fields=["event_type", "status"], name="markets_mar_event_t_822343_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketproposal",
            index=models.Index(
                fields=["status", "-submitted_at"], name="markets_mar_status_8f8242_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketproposalreview",
            index=models.Index(
                fields=["proposal", "-created_at", "-id"], name="markets_mar_proposa_7d9f5e_idx"
            ),
        ),
    ]
