# Generated by Django 5.2.16 on 2026-08-03 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0012_marketeventgroup_market_event_group_marketproposal_and_more"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="duplicate_fingerprint",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="marketeventgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sporting_event__isnull", False)),
                fields=("sporting_event",),
                name="unique_market_group_per_sporting_event",
            ),
        ),
    ]
