# Generated by Django 5.2.16 on 2026-08-03 18:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0013_market_duplicate_fingerprint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketRecentView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_viewed_at", models.DateTimeField()),
                ("last_viewed_at", models.DateTimeField()),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_views",
                        to="markets.market",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_recent_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_viewed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["participant", "-last_viewed_at"],
                        name="markets_mar_partici_e4aafc_idx",
                    ),
                    models.Index(
                        fields=["market", "last_viewed_at"], name="markets_mar_market__2c690f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("participant", "market"), name="unique_market_recent_view"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("view_count__gte", 1)),
                        name="market_recent_view_count_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("first_viewed_at__lte", models.F("last_viewed_at"))),
                        name="market_recent_view_timestamps_ordered",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketWatchlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("followed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_entries",
                        to="markets.market",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_watchlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-followed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["participant", "-followed_at"],
                        name="markets_mar_partici_683fd6_idx",
                    ),
                    models.Index(
                        fields=["market", "followed_at"], name="markets_mar_market__a21a98_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("participant", "market"), name="unique_market_watchlist_entry"
                    )
                ],
            },
        ),
    ]
