# Generated by Django 5.2.16 on 2026-08-04 10:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0014_marketrecentview_marketwatchlistentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketProvisionalResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField()),
                ("publisher_email", models.EmailField(max_length=254)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("dispute_deadline", models.DateTimeField(db_index=True)),
                (
                    "market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provisional_result",
                        to="markets.market",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_market_provisional_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winning_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provisional_results",
                        to="markets.marketoutcome",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketProvisionalEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("OFFICIAL_RESULT", "Official result"),
                            ("DOCUMENT_REFERENCE", "Document reference"),
                            ("OFFICIAL_SOURCE", "Official source"),
                            ("MEDIA_REFERENCE", "Media reference"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("reference", models.TextField()),
                ("recorder_email", models.EmailField(max_length=254)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_market_provisional_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provisional_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_items",
                        to="markets.marketprovisionalresult",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="marketprovisionalresult",
            index=models.Index(fields=["dispute_deadline"], name="mkt_prov_deadline_idx"),
        ),
        migrations.AddIndex(
            model_name="marketprovisionalresult",
            index=models.Index(
                fields=["published_by", "-published_at"], name="mkt_prov_publisher_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketprovisionalresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("dispute_deadline__gt", models.F("published_at"))),
                name="market_provisional_deadline_after_publish",
            ),
        ),
        migrations.AddIndex(
            model_name="marketprovisionalevidence",
            index=models.Index(
                fields=["provisional_result", "recorded_at"], name="mkt_prov_evidence_idx"
            ),
        ),
    ]
