# Generated by Django 5.2.16 on 2026-08-04 11:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0015_marketprovisionalresult_marketprovisionalevidence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketResultDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("participant_email", models.EmailField(max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("INCORRECT_OUTCOME", "Incorrect outcome"),
                            ("INCOMPLETE_EVIDENCE", "Incomplete evidence"),
                            ("SOURCE_CONFLICT", "Conflicting official sources"),
                            ("RULES_APPLICATION", "Incorrect rules application"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("explanation", models.TextField()),
                ("submitted_at", models.DateTimeField(db_index=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_result_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provisional_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="markets.marketprovisionalresult",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketResultDisputeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=255)),
                ("reference", models.TextField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_items",
                        to="markets.marketresultdispute",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="marketresultdispute",
            index=models.Index(
                fields=["provisional_result", "submitted_at"], name="mkt_dispute_result_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketresultdispute",
            index=models.Index(
                fields=["participant", "-submitted_at"], name="mkt_dispute_part_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketresultdispute",
            constraint=models.UniqueConstraint(
                fields=("provisional_result", "participant"), name="uniq_mkt_result_dispute"
            ),
        ),
        migrations.AddIndex(
            model_name="marketresultdisputeevidence",
            index=models.Index(fields=["dispute", "recorded_at"], name="mkt_dispute_evid_idx"),
        ),
    ]
