# Generated by Django 5.2.16 on 2026-08-04 12:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0016_marketresultdispute_marketresultdisputeevidence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketResultDisputeDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("CONFIRM", "Confirm provisional result"),
                            ("CORRECT", "Correct provisional result"),
                            ("VOID", "Void market"),
                            ("EXTEND_REVIEW", "Extend review"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "review_extended_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("covered_dispute_count", models.PositiveIntegerField()),
                ("notes", models.TextField()),
                ("evidence", models.TextField()),
                ("decision_maker_email", models.EmailField(max_length=254)),
                ("decided_at", models.DateTimeField(db_index=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_result_dispute_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provisional_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="markets.marketprovisionalresult",
                    ),
                ),
                (
                    "winning_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_dispute_decisions",
                        to="markets.marketoutcome",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
                "indexes": [
                    models.Index(
                        fields=["provisional_result", "sequence"], name="mkt_dispute_dec_seq_idx"
                    ),
                    models.Index(
                        fields=["decided_by", "-decided_at"], name="mkt_dispute_decider_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provisional_result", "sequence"), name="uniq_mkt_dispute_dec_seq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("decision_type__in", ["CONFIRM", "CORRECT", "VOID"])),
                        fields=("provisional_result",),
                        name="uniq_mkt_dispute_final",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)), name="mkt_dispute_dec_seq_gte1"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("covered_dispute_count__gte", 1)),
                        name="mkt_dispute_count_gte1",
                    ),
                ],
            },
        ),
    ]
