# Generated by Django 5.2.16 on 2026-08-04 13:47

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0017_marketresultdisputedecision"),
        ("wallets", "0001_wallet_ledger_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketOrderExpiryAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("SYSTEM", "System"), ("ADMIN", "Administrator")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OPEN", "Open"),
                            ("PARTIALLY_FILLED", "Partially filled"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("expired_quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "released_wallet_reservation_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20),
                ),
                (
                    "released_position_reservation_quantity",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                ("reason", models.TextField()),
                ("expired_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-expired_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="marketorder",
            name="expired_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="time_in_force",
            field=models.CharField(
                choices=[
                    ("GTC", "Good till cancelled"),
                    ("GTD", "Good till date"),
                    ("IOC", "Immediate or cancel"),
                    ("FOK", "Fill or kill"),
                ],
                db_index=True,
                default="GTC",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="marketorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OPEN", "Open"),
                    ("PARTIALLY_FILLED", "Partially filled"),
                    ("FILLED", "Filled"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="marketorder",
            index=models.Index(
                fields=["time_in_force", "status", "expires_at"], name="mkt_order_expiry_due_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("expires_at__isnull", False), ("time_in_force", "GTD")),
                    models.Q(
                        ("expires_at__isnull", True), ("time_in_force__in", ["GTC", "IOC", "FOK"])
                    ),
                    _connector="OR",
                ),
                name="market_order_tif_expiry_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("expired_at__isnull", False), ("status", "EXPIRED")),
                    models.Q(
                        models.Q(("status", "EXPIRED"), _negated=True), ("expired_at__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="market_order_expired_at_consistent",
            ),
        ),
        migrations.AddField(
            model_name="marketorderexpiryaudit",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="market_order_expiry_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marketorderexpiryaudit",
            name="market_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expiry_audit",
                to="markets.marketorder",
            ),
        ),
        migrations.AddField(
            model_name="marketorderexpiryaudit",
            name="wallet_release_ledger_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="market_order_expiry_audit",
                to="wallets.ledgerentry",
            ),
        ),
        migrations.AddIndex(
            model_name="marketorderexpiryaudit",
            index=models.Index(fields=["source", "-expired_at"], name="mkt_order_exp_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="marketorderexpiryaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(("expired_quantity__gt", 0)), name="mkt_order_exp_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketorderexpiryaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(("released_wallet_reservation_amount__gte", 0)),
                name="mkt_order_exp_cash_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketorderexpiryaudit",
            constraint=models.CheckConstraint(
                condition=models.Q(("released_position_reservation_quantity__gte", 0)),
                name="mkt_order_exp_shares_nonneg",
            ),
        ),
    ]
