# Generated by Django 5.2.16 on 2026-08-04 14:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0018_add_market_order_expiry_tif"),
        ("wallets", "0001_wallet_ledger_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketReconciliationMismatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("market_id_snapshot", models.UUIDField(null=True)),
                ("participant_id_snapshot", models.UUIDField(null=True)),
                ("wallet_id_snapshot", models.UUIDField(null=True)),
                ("order_id_snapshot", models.UUIDField(null=True)),
                ("fill_id_snapshot", models.UUIDField(null=True)),
                ("expected_value", models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ("actual_value", models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ("unit", models.CharField(blank=True, max_length=12)),
                ("explanation", models.TextField()),
                ("detected_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="marketorder",
            name="maximum_fee_bps",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketpositionsettlement",
            name="net_payout_amount",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="marketpositionsettlement",
            name="payout_fee_amount",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="marketpositionvoidrefund",
            name="net_refund_amount",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="marketpositionvoidrefund",
            name="refund_fee_amount",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
        ),
        migrations.CreateModel(
            name="MarketFeeSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("RETIRED", "Retired")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("maker_fee_bps", models.PositiveIntegerField(default=0)),
                ("taker_fee_bps", models.PositiveIntegerField(default=0)),
                ("settlement_fee_bps", models.PositiveIntegerField(default=0)),
                ("refund_fee_bps", models.PositiveIntegerField(default=0)),
                ("effective_at", models.DateTimeField()),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activated_fee_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_fee_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_schedules",
                        to="markets.market",
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retired_fee_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketFeeLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_reference", models.UUIDField(unique=True)),
                ("schedule_version", models.PositiveIntegerField(default=0)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("MAKER", "Maker"),
                            ("TAKER", "Taker"),
                            ("SETTLEMENT", "Settlement"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=12,
                    ),
                ),
                ("rate_bps", models.PositiveIntegerField()),
                ("gross_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("fee_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("net_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "fill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_entries",
                        to="markets.marketfill",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_entries",
                        to="markets.market",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_entries",
                        to="markets.marketorder",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_fee_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="markets.marketfeeschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="marketorder",
            name="fee_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="markets.marketfeeschedule",
            ),
        ),
        migrations.CreateModel(
            name="MarketFinancialAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("evidence_reference", models.CharField(max_length=255)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("executed_at", models.DateTimeField(null=True)),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_adjustments",
                        to="markets.market",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposed_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mismatch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="markets.marketreconciliationmismatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketFinancialAdjustmentApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")], max_length=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "adjustment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval",
                        to="markets.marketfinancialadjustment",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketFinancialAdjustmentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], max_length=6
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("idempotency_reference", models.UUIDField(unique=True)),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="markets.marketfinancialadjustment",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_adjustment_lines",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "wallet_ledger_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_adjustment_line",
                        to="wallets.ledgerentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketReconciliationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.UUIDField(unique=True)),
                ("run_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("order_count", models.PositiveIntegerField(default=0)),
                ("fill_count", models.PositiveIntegerField(default=0)),
                ("mismatch_count", models.PositiveIntegerField(default=0)),
                (
                    "total_fee_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_reconciliation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_runs",
                        to="markets.market",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_reconciliation_runs",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="marketreconciliationmismatch",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mismatches",
                to="markets.marketreconciliationrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfeeschedule",
            constraint=models.UniqueConstraint(
                fields=("market", "version"), name="mkt_fee_scope_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfeeschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("maker_fee_bps__lte", 1000)), name="mkt_fee_maker_bps_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfeeschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("taker_fee_bps__lte", 1000)), name="mkt_fee_taker_bps_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfeeschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("settlement_fee_bps__lte", 1000)), name="mkt_fee_settle_bps_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfeeschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_fee_bps__lte", 1000)), name="mkt_fee_refund_bps_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfeeledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate_bps__lte", 1000)), name="mkt_fee_entry_rate_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfeeledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("gross_amount__gte", 0)), name="mkt_fee_gross_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfeeledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("fee_amount__gte", 0)), name="mkt_fee_amount_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfeeledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("net_amount__gte", 0)), name="mkt_fee_net_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketfinancialadjustmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="mkt_adjust_line_positive"
            ),
        ),
    ]
