# Generated by Django 5.2.16 on 2026-08-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0019_marketreconciliationmismatch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketfeeledgerentry",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="markets.marketfeeschedule",
            ),
        ),
    ]
