# Generated by Django 5.2.16 on 2026-08-04 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0020_alter_marketfeeledgerentry_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="marketfeeschedule",
            name="mkt_fee_scope_version_uniq",
        ),
        migrations.AddConstraint(
            model_name="marketfeeschedule",
            constraint=models.UniqueConstraint(
                fields=("market", "version"),
                name="mkt_fee_scope_version_uniq",
                nulls_distinct=False,
            ),
        ),
    ]
