# Generated by Django 5.2.16 on 2026-08-04 18:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0021_remove_marketfeeschedule_mkt_fee_scope_version_uniq_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="marketcompliancereview",
            name="source",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("PROVIDER", "Provider"),
                    ("SYSTEM", "System"),
                ],
                default="ADMIN",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="marketcompliancereview",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="market_compliance_audits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="KYCVerificationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_code", models.CharField(db_index=True, max_length=64)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("client_idempotency_key", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PENDING", "Pending"),
                            ("IN_REVIEW", "In review"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=16,
                    ),
                ),
                ("provider_status", models.CharField(blank=True, max_length=100)),
                ("verification_level", models.CharField(default="STANDARD", max_length=50)),
                ("initiated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("continuation_url", models.URLField(blank=True, max_length=500)),
                ("failure_code", models.CharField(blank=True, max_length=100)),
                ("status_message", models.CharField(blank=True, max_length=500)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_kyc_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kyc_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-initiated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="KYCVerificationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=64)),
                ("previous_status", models.CharField(blank=True, max_length=16)),
                ("new_status", models.CharField(max_length=16)),
                ("provider_status", models.CharField(blank=True, max_length=100)),
                ("external_event_id", models.CharField(blank=True, max_length=255, null=True)),
                ("payload_digest", models.CharField(db_index=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PARTICIPANT", "Participant"),
                            ("PROVIDER", "Provider"),
                            ("ADMIN", "Administrator"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kyc_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="markets.kycverificationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="MarketRiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason_codes", models.JSONField(default=list)),
                ("input_summary", models.JSONField(default=dict)),
                ("recommended_action", models.CharField(max_length=32)),
                ("assessment_source", models.CharField(default="SYSTEM", max_length=16)),
                ("input_digest", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_risk_assessment_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_risk_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketRiskProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "risk_band",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "restriction_recommendation",
                    models.CharField(db_index=True, default="NONE", max_length=32),
                ),
                ("reason_codes", models.JSONField(default=list)),
                ("last_assessed_at", models.DateTimeField(blank=True, null=True)),
                ("assessment_source", models.CharField(default="SYSTEM", max_length=16)),
                ("manual_override_state", models.CharField(default="NONE", max_length=16)),
                ("manual_override_reason", models.TextField(blank=True)),
                ("override_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "override_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_risk_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_risk_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="kycverificationsession",
            constraint=models.UniqueConstraint(
                fields=("participant", "client_idempotency_key"),
                name="kyc_participant_idempotency_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="kycverificationevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_event_id__isnull", False)),
                fields=("session", "external_event_id"),
                name="kyc_session_external_event_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketriskassessment",
            constraint=models.UniqueConstraint(
                fields=("participant", "input_digest"), name="risk_participant_input_uniq"
            ),
        ),
    ]
