# Generated by Django 5.2.16 on 2026-08-04 18:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0022_marketcompliancereview_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceDecisionProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("CLEAR_CRITICAL_RISK_BLOCK", "Clear critical risk block"),
                            ("REMOVE_SUSPENDED_RESTRICTION", "Remove suspension"),
                            ("JURISDICTION_BLOCK_TO_ALLOW", "Allow jurisdiction"),
                            ("APPLY_RISK_OVERRIDE", "Apply risk override"),
                            ("CLEAR_RISK_OVERRIDE", "Clear risk override"),
                        ],
                        max_length=40,
                    ),
                ),
                ("requested_change", models.JSONField(default=dict)),
                ("reason", models.TextField()),
                ("before_snapshot", models.JSONField(default=dict)),
                ("proposed_after_snapshot", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("decision_reason", models.TextField(blank=True)),
                ("proposed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_compliance_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposed_compliance_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-proposed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-proposed_at"], name="markets_com_status_03fd7c_idx"
                    )
                ],
            },
        ),
    ]
