# Generated by Django 5.2.17 on 2026-08-14 12:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0024_market_opening_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketResultDevelopmentAcceleration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accelerated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.CharField(default="Development testing only", max_length=255)),
                (
                    "accelerated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_development_accelerations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provisional_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="development_acceleration",
                        to="markets.marketprovisionalresult",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
