# Generated by Django 5.2.17 on 2026-08-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0025_marketresultdevelopmentacceleration"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="settles_by",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
