# Generated by Django 5.2.17 on 2026-08-14 21:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0026_market_settles_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketCollateralPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "locked_collateral",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "settled_collateral",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "released_collateral",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SETTLED", "Settled"),
                            ("RELEASED", "Released"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collateral_pool",
                        to="markets.market",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketLiquidityProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("PLATFORM_TREASURY", "Platform treasury"),
                            ("EXTERNAL_MARKET_MAKER", "External market maker"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_name", models.CharField(max_length=160)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidity_provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketLiquidityConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PLATFORM_TREASURY", "Platform treasury"),
                            ("EXTERNAL_MARKET_MAKER", "External market maker"),
                        ],
                        default="PLATFORM_TREASURY",
                        max_length=40,
                    ),
                ),
                (
                    "initial_liquidity_ugx",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("opening_spread_bps", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNCONFIGURED", "Unconfigured"),
                            ("CONFIGURED", "Configured"),
                            ("ACTIVE", "Active"),
                            ("EXHAUSTED", "Exhausted"),
                            ("CLOSED", "Closed"),
                        ],
                        default="UNCONFIGURED",
                        max_length=20,
                    ),
                ),
                ("configured_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configured_market_liquidity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidity_configuration",
                        to="markets.market",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_configurations",
                        to="markets.marketliquidityprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketCompleteSetIssuance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issuance_type",
                    models.CharField(
                        choices=[
                            ("PLATFORM_OPENING", "Platform opening"),
                            ("COMPLEMENTARY_BUYS", "Complementary buys"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("collateral_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("yes_execution_price", models.DecimalField(decimal_places=5, max_digits=6)),
                ("no_execution_price", models.DecimalField(decimal_places=5, max_digits=6)),
                ("idempotency_reference", models.UUIDField(unique=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complete_set_issuances",
                        to="markets.market",
                    ),
                ),
                (
                    "no_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="no_complete_set_issuances",
                        to="markets.marketorder",
                    ),
                ),
                (
                    "yes_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yes_complete_set_issuances",
                        to="markets.marketorder",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuances",
                        to="markets.marketliquidityprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketCollateralEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("TREASURY_LOCK", "Treasury lock"),
                            ("COMPLEMENTARY_BUY_LOCK", "Complementary buy lock"),
                            ("SETTLEMENT_PAYOUT", "Settlement payout"),
                            ("VOID_RELEASE", "Void release"),
                            ("TREASURY_RELEASE", "Treasury release"),
                        ],
                        max_length=40,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("idempotency_reference", models.UUIDField(unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_collateral_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collateral_entries",
                        to="markets.market",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collateral_entries",
                        to="markets.marketorder",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="markets.marketcollateralpool",
                    ),
                ),
                (
                    "issuance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collateral_entries",
                        to="markets.marketcompletesetissuance",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collateral_entries",
                        to="markets.marketliquidityprovider",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="marketcollateralpool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("locked_collateral__gte", 0),
                    ("settled_collateral__gte", 0),
                    ("released_collateral__gte", 0),
                ),
                name="market_collateral_balances_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketliquidityconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("initial_liquidity_ugx__gte", 0)),
                name="market_liquidity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketliquidityconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("opening_spread_bps__lte", 5000)),
                name="market_liquidity_spread_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketcollateralentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="market_collateral_entry_amount_positive",
            ),
        ),
    ]
