# Generated by Django 5.2.17 on 2026-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0028_merge_20260815_hybrid_liquidity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketstatustransition",
            name="action",
            field=models.CharField(
                choices=[
                    ("SUBMIT", "Submit for approval"),
                    ("APPROVE", "Approve"),
                    ("REJECT", "Reject"),
                    ("REVERT_TO_DRAFT", "Revert to draft"),
                    ("OPEN", "Open"),
                    ("SUSPEND", "Suspend"),
                    ("REOPEN", "Reopen"),
                    ("CLOSE", "Close"),
                    ("RESOLVE", "Resolve"),
                    ("VOID", "Void"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
