# Generated by Django 5.2.17 on 2026-08-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0028_merge_20260815_hybrid_liquidity"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="is_catalog_visible",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
