# Generated by Django 5.2.14 on 2026-08-15 13:18

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0028_merge_20260815_hybrid_liquidity"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="close_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAXIMUM_AMOUNT_REACHED", "Maximum amount reached"),
                    ("SCHEDULED_CLOSE", "Scheduled close"),
                    ("ADMIN_CLOSED", "Admin closed"),
                ],
                db_index=True,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="current_market_amount",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Current executed BUY volume counting toward market capacity.",
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="max_market_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Maximum UGX trading volume for this market.",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="settlement_unit",
            field=models.PositiveIntegerField(
                default=5000,
                help_text="UGX payout per winning share unit.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="For MARKET BUY orders: UGX amount to spend.",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="order_type",
            field=models.CharField(
                choices=[("MARKET", "Market"), ("LIMIT", "Limit")],
                db_index=True,
                default="LIMIT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="face_value_ugx",
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["status", "current_market_amount"], name="market_capacity_idx"
            ),
        ),
    ]
