# Generated by Django 5.2.17 on 2026-09-07 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0029_market_catalog_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPositionExit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opened_at", models.DateTimeField()),
                ("exited_at", models.DateTimeField()),
                ("acquired_quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("exited_quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("cost_basis", models.DecimalField(decimal_places=4, max_digits=20)),
                ("realized_proceeds", models.DecimalField(decimal_places=4, max_digits=20)),
                ("realized_pnl", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "closing_fill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_exit",
                        to="markets.marketfill",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_exits",
                        to="markets.market",
                    ),
                ),
                (
                    "market_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exit_history",
                        to="markets.marketposition",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_exits",
                        to="markets.marketoutcome",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_position_exit_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-exited_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["participant", "-exited_at"], name="markets_mar_partici_d4f6a7_idx"
                    )
                ],
            },
        ),
    ]
