# Generated by Django 5.2.17 on 2026-09-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0029_alter_marketstatustransition_action"),
        ("markets", "0029_market_catalog_visibility"),
    ]

    operations = []
