# Generated by Django 5.2.14 on 2026-08-04 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(db_index=True, default=False)),
                (
                    "rollout_percentage",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Percentage of users for whom this flag is active (0-100).",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        default="ALL",
                        help_text="Environment this flag applies to (ALL, dev, staging, production).",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feature flag",
                "verbose_name_plural": "Feature flags",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=200, unique=True)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Whether this configuration is exposed to clients."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System configuration",
                "verbose_name_plural": "System configurations",
                "ordering": ["key"],
            },
        ),
    ]
