# Generated by Django 5.2.16 on 2026-07-31 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TEAM", "Team"),
                            ("ATHLETE", "Athlete"),
                            ("COUNTRY", "Country or national team"),
                            ("PAIR", "Pair"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="TEAM",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("short_name", models.CharField(blank=True, max_length=80)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["sport__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("AWAY", "Away"),
                            ("COMPETITOR", "Competitor"),
                            ("SUBJECT", "Subject"),
                            ("OTHER", "Other"),
                        ],
                        default="COMPETITOR",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_entries",
                        to="sports.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["event", "position"],
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="sports.sport",
            ),
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("country_code", models.CharField(default="UG", max_length=2)),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitions",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "ordering": ["sport__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="SportingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MATCH", "Match"),
                            ("RACE", "Race"),
                            ("TOURNAMENT", "Tournament"),
                            ("BOUT", "Bout"),
                            ("SERIES", "Series"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="MATCH",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("LIVE", "Live"),
                            ("COMPLETED", "Completed"),
                            ("POSTPONED", "Postponed"),
                            ("CANCELLED", "Cancelled"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="sports.competition",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="events",
                        through="sports.EventParticipant",
                        to="sports.participant",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "name"],
            },
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_participants",
                to="sports.sportingevent",
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["sport", "kind", "is_active"], name="sports_part_sport_i_214932_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["country_code", "is_active"], name="sports_part_country_76ffa7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("sport", "kind", "country_code", "slug"),
                name="unique_sport_participant_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                fields=("source_name", "source_reference"),
                name="unique_participant_source_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(
                fields=["sport", "is_active"], name="sports_comp_sport_i_c89cd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(
                fields=["country_code", "is_active"], name="sports_comp_country_66ef5a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="competition",
            constraint=models.UniqueConstraint(
                fields=("sport", "country_code", "slug"), name="unique_competition_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="competition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                fields=("source_name", "source_reference"),
                name="unique_competition_source_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="sportingevent",
            index=models.Index(
                fields=["sport", "starts_at"], name="sports_spor_sport_i_49a87d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sportingevent",
            index=models.Index(
                fields=["competition", "starts_at"], name="sports_spor_competi_54ddb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sportingevent",
            index=models.Index(
                fields=["status", "starts_at"], name="sports_spor_status_16ebd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sportingevent",
            index=models.Index(
                fields=["is_verified", "starts_at"], name="sports_spor_is_veri_b8a310_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sportingevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_verified", False), ("verified_at__isnull", False), _connector="OR"
                ),
                name="verified_sporting_event_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="sportingevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                fields=("source_name", "source_reference"),
                name="unique_sporting_event_source_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(fields=["event", "role"], name="sports_even_event_i_b35f51_idx"),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(
                fields=["participant", "event"], name="sports_even_partici_7faa6a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.UniqueConstraint(
                fields=("event", "participant"), name="unique_participant_per_sporting_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.UniqueConstraint(
                fields=("event", "position"), name="unique_participant_position_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role__in", ["HOME", "AWAY"])),
                fields=("event", "role"),
                name="unique_home_away_role_per_event",
            ),
        ),
    ]
