from django.urls import path

from markets.admin_views import (
    MarketAdminDetailView,
    MarketAdminListCreateView,
)
from markets.compliance_admin_views import (
    AdminComplianceDecisionDecideView,
    AdminComplianceDecisionDetailView,
    AdminComplianceDecisionListCreateView,
    AdminKYCSessionDetailView,
    AdminKYCSessionListView,
    AdminRiskAssessmentListView,
    AdminRiskProfileDetailView,
    AdminRiskProfileListView,
    AdminRiskReassessView,
)
from markets.compliance_views import (
    AdminParticipantComplianceDetailView,
    AdminParticipantComplianceReviewListView,
    MarketParticipantEligibilityView,
)
from markets.discovery_views import (
    MarketDiscoveryView,
    MarketRecentlyViewedItemView,
    MarketRecentlyViewedView,
    MarketWatchlistItemView,
    MarketWatchlistView,
)
from markets.event_views import (
    AdminMarketEventArchiveView,
    AdminMarketEventAttachView,
    AdminMarketEventDetachView,
    AdminMarketEventDetailView,
    AdminMarketEventListCreateView,
    AdminMarketEventPublishView,
    MarketEventDetailView,
    MarketEventListView,
    MarketEventMarketListView,
)
from markets.financial_integrity_views import (
    AdjustmentApproveView,
    AdjustmentDetailView,
    AdjustmentListView,
    AdjustmentProposeView,
    AdjustmentRejectView,
    FeePreviewView,
    FeeScheduleActivateView,
    FeeScheduleDetailView,
    FeeScheduleListCreateView,
    FeeScheduleRetireView,
    ReconciliationExportView,
    ReconciliationMismatchDetailView,
    ReconciliationMismatchListView,
    ReconciliationRunDetailView,
    ReconciliationRunListView,
    ReconciliationStartView,
)
from markets.kyc_views import (
    KYCCallbackView,
    KYCComplianceSummaryView,
    KYCSessionCancelView,
    KYCSessionDetailView,
    KYCSessionListStartView,
)
from markets.lifecycle_views import (
    MarketApproveView,
    MarketCloseView,
    MarketOpenView,
    MarketRejectView,
    MarketReopenView,
    MarketSubmitView,
    MarketSuspendView,
)
from markets.open_order_views import ParticipantOpenOrderListView
from markets.order_book_views import MarketOrderBookView
from markets.participation_views import (
    MarketFillDetailView,
    MarketFillListView,
    MarketOrderCancelView,
    MarketOrderCreateView,
    MarketOrderDetailView,
    MarketOrderListView,
    MarketPositionDetailView,
    MarketPositionListView,
)
from markets.portfolio_activity_views import MarketPortfolioActivityListView
from markets.portfolio_views import (
    MarketPortfolioPositionListView,
    MarketPortfolioSummaryView,
)
from markets.price_history_views import MarketOutcomePriceHistoryView
from markets.proposal_views import (
    AdminMarketProposalDetailView,
    AdminMarketProposalListView,
    AdminMarketProposalReviewListView,
    AdminMarketProposalReviewView,
    MarketProposalDetailView,
    MarketProposalListCreateView,
    MarketProposalWithdrawView,
)
from markets.provisional_result_views import (
    MarketProvisionalResultDetailView,
    MarketProvisionalResultPublishView,
)
from markets.resolution_views import (
    MarketResolveView,
    MarketVoidView,
)
from markets.responsible_participation_views import (
    AdminResponsibleEventListView,
    AdminResponsibleParticipationView,
    CoolingOffView,
    ParticipantResponsibleEventListView,
    ResponsibleParticipationView,
    SelfExclusionView,
)
from markets.result_dispute_decision_views import (
    AdminMarketResultDisputeDecisionCreateView,
    AdminMarketResultDisputeDecisionDetailView,
    MarketResultDisputeDecisionListView,
)
from markets.result_dispute_views import (
    AdminMarketResultDisputeDetailView,
    AdminMarketResultDisputeListView,
    MarketResultDisputeSubmitView,
    ParticipantMarketResultDisputeDetailView,
    ParticipantMarketResultDisputeListView,
)
from markets.settlement_views import MarketSettlementView
from markets.stats_views import MarketStatsView
from markets.views import (
    MarketCategoryListView,
    MarketDetailView,
    MarketListView,
)
from markets.void_refund_views import MarketVoidRefundView

app_name = "markets"

urlpatterns = [
    path(
        "admin/compliance/kyc-sessions/", AdminKYCSessionListView.as_view(), name="admin-kyc-list"
    ),
    path(
        "admin/compliance/kyc-sessions/<uuid:session_id>/",
        AdminKYCSessionDetailView.as_view(),
        name="admin-kyc-detail",
    ),
    path(
        "admin/compliance/risk-profiles/",
        AdminRiskProfileListView.as_view(),
        name="admin-risk-list",
    ),
    path(
        "admin/compliance/risk-profiles/<uuid:profile_id>/",
        AdminRiskProfileDetailView.as_view(),
        name="admin-risk-detail",
    ),
    path(
        "admin/compliance/risk-assessments/",
        AdminRiskAssessmentListView.as_view(),
        name="admin-risk-assessments",
    ),
    path(
        "admin/compliance/risk-reassess/",
        AdminRiskReassessView.as_view(),
        name="admin-risk-reassess",
    ),
    path(
        "admin/compliance/decisions/",
        AdminComplianceDecisionListCreateView.as_view(),
        name="admin-decision-list",
    ),
    path(
        "admin/compliance/decisions/<uuid:proposal_id>/",
        AdminComplianceDecisionDetailView.as_view(),
        name="admin-decision-detail",
    ),
    path(
        "admin/compliance/decisions/<uuid:proposal_id>/decide/",
        AdminComplianceDecisionDecideView.as_view(),
        name="admin-decision-decide",
    ),
    path("markets/kyc/sessions/", KYCSessionListStartView.as_view(), name="market-kyc-sessions"),
    path(
        "markets/kyc/sessions/<uuid:session_id>/",
        KYCSessionDetailView.as_view(),
        name="market-kyc-session-detail",
    ),
    path(
        "markets/kyc/sessions/<uuid:session_id>/cancel/",
        KYCSessionCancelView.as_view(),
        name="market-kyc-session-cancel",
    ),
    path("markets/kyc/summary/", KYCComplianceSummaryView.as_view(), name="market-kyc-summary"),
    path(
        "markets/kyc/providers/<str:provider>/callback/",
        KYCCallbackView.as_view(),
        name="market-kyc-callback",
    ),
    path(
        "markets/<uuid:market_id>/orders/fee-preview/",
        FeePreviewView.as_view(),
        name="market-order-fee-preview",
    ),
    path(
        "market-admin/fee-schedules/",
        FeeScheduleListCreateView.as_view(),
        name="market-fee-schedule-list-create",
    ),
    path(
        "market-admin/fee-schedules/<uuid:schedule_id>/",
        FeeScheduleDetailView.as_view(),
        name="market-fee-schedule-detail",
    ),
    path(
        "market-admin/fee-schedules/<uuid:schedule_id>/activate/",
        FeeScheduleActivateView.as_view(),
        name="market-fee-schedule-activate",
    ),
    path(
        "market-admin/fee-schedules/<uuid:schedule_id>/retire/",
        FeeScheduleRetireView.as_view(),
        name="market-fee-schedule-retire",
    ),
    path(
        "market-admin/reconciliation/start/",
        ReconciliationStartView.as_view(),
        name="market-reconciliation-start",
    ),
    path(
        "market-admin/reconciliation/runs/",
        ReconciliationRunListView.as_view(),
        name="market-reconciliation-run-list",
    ),
    path(
        "market-admin/reconciliation/runs/<uuid:run_id>/",
        ReconciliationRunDetailView.as_view(),
        name="market-reconciliation-run-detail",
    ),
    path(
        "market-admin/reconciliation/runs/<uuid:run_id>/export/",
        ReconciliationExportView.as_view(),
        name="market-reconciliation-export",
    ),
    path(
        "market-admin/reconciliation/mismatches/",
        ReconciliationMismatchListView.as_view(),
        name="market-reconciliation-mismatch-list",
    ),
    path(
        "market-admin/reconciliation/mismatches/<uuid:mismatch_id>/",
        ReconciliationMismatchDetailView.as_view(),
        name="market-reconciliation-mismatch-detail",
    ),
    path(
        "market-admin/financial-adjustments/",
        AdjustmentListView.as_view(),
        name="market-adjustment-list",
    ),
    path(
        "market-admin/financial-adjustments/propose/",
        AdjustmentProposeView.as_view(),
        name="market-adjustment-propose",
    ),
    path(
        "market-admin/financial-adjustments/<uuid:adjustment_id>/",
        AdjustmentDetailView.as_view(),
        name="market-adjustment-detail",
    ),
    path(
        "market-admin/financial-adjustments/<uuid:adjustment_id>/approve/",
        AdjustmentApproveView.as_view(),
        name="market-adjustment-approve",
    ),
    path(
        "market-admin/financial-adjustments/<uuid:adjustment_id>/reject/",
        AdjustmentRejectView.as_view(),
        name="market-adjustment-reject",
    ),
    path("markets/watchlist/", MarketWatchlistView.as_view(), name="market-watchlist"),
    path(
        "markets/watchlist/<uuid:market_id>/",
        MarketWatchlistItemView.as_view(),
        name="market-watchlist-item",
    ),
    path(
        "markets/recently-viewed/",
        MarketRecentlyViewedView.as_view(),
        name="market-recently-viewed",
    ),
    path(
        "markets/recently-viewed/<uuid:market_id>/",
        MarketRecentlyViewedItemView.as_view(),
        name="market-recently-viewed-item",
    ),
    path("markets/discovery/", MarketDiscoveryView.as_view(), name="market-discovery"),
    path("market-events/", MarketEventListView.as_view(), name="market-event-list"),
    path(
        "market-events/<uuid:event_id>/",
        MarketEventDetailView.as_view(),
        name="market-event-detail",
    ),
    path(
        "market-events/<uuid:event_id>/markets/",
        MarketEventMarketListView.as_view(),
        name="market-event-market-list",
    ),
    path(
        "market-admin/events/",
        AdminMarketEventListCreateView.as_view(),
        name="admin-market-event-list-create",
    ),
    path(
        "market-admin/events/<uuid:event_id>/",
        AdminMarketEventDetailView.as_view(),
        name="admin-market-event-detail",
    ),
    path(
        "market-admin/events/<uuid:event_id>/publish/",
        AdminMarketEventPublishView.as_view(),
        name="admin-market-event-publish",
    ),
    path(
        "market-admin/events/<uuid:event_id>/archive/",
        AdminMarketEventArchiveView.as_view(),
        name="admin-market-event-archive",
    ),
    path(
        "market-admin/events/<uuid:event_id>/markets/",
        AdminMarketEventAttachView.as_view(),
        name="admin-market-event-attach-market",
    ),
    path(
        "market-admin/events/<uuid:event_id>/markets/<uuid:market_id>/",
        AdminMarketEventDetachView.as_view(),
        name="admin-market-event-detach-market",
    ),
    path(
        "markets/proposals/",
        MarketProposalListCreateView.as_view(),
        name="market-proposal-list-create",
    ),
    path(
        "markets/proposals/<uuid:proposal_id>/",
        MarketProposalDetailView.as_view(),
        name="market-proposal-detail",
    ),
    path(
        "markets/proposals/<uuid:proposal_id>/withdraw/",
        MarketProposalWithdrawView.as_view(),
        name="market-proposal-withdraw",
    ),
    path(
        "market-admin/proposals/",
        AdminMarketProposalListView.as_view(),
        name="admin-market-proposal-list",
    ),
    path(
        "market-admin/proposals/<uuid:proposal_id>/",
        AdminMarketProposalDetailView.as_view(),
        name="admin-market-proposal-detail",
    ),
    path(
        "market-admin/proposals/<uuid:proposal_id>/review/",
        AdminMarketProposalReviewView.as_view(),
        name="admin-market-proposal-review",
    ),
    path(
        "market-admin/proposals/<uuid:proposal_id>/reviews/",
        AdminMarketProposalReviewListView.as_view(),
        name="admin-market-proposal-review-list",
    ),
    path(
        "markets/responsible-participation/",
        ResponsibleParticipationView.as_view(),
        name="market-responsible-participation",
    ),
    path(
        "markets/responsible-participation/cooling-off/",
        CoolingOffView.as_view(),
        name="market-responsible-participation-cooling-off",
    ),
    path(
        "markets/responsible-participation/self-exclusion/",
        SelfExclusionView.as_view(),
        name="market-responsible-participation-self-exclusion",
    ),
    path(
        "markets/responsible-participation/events/",
        ParticipantResponsibleEventListView.as_view(),
        name="market-responsible-participation-events",
    ),
    path(
        "market-admin/participants/<uuid:user_id>/responsible-participation/",
        AdminResponsibleParticipationView.as_view(),
        name="admin-participant-responsible-participation",
    ),
    path(
        "market-admin/participants/<uuid:user_id>/responsible-participation/events/",
        AdminResponsibleEventListView.as_view(),
        name="admin-participant-responsible-participation-events",
    ),
    path(
        "markets/eligibility/",
        MarketParticipantEligibilityView.as_view(),
        name="market-participant-eligibility",
    ),
    path(
        "market-admin/participants/<uuid:user_id>/compliance/",
        AdminParticipantComplianceDetailView.as_view(),
        name="admin-participant-compliance-detail",
    ),
    path(
        "market-admin/participants/<uuid:user_id>/compliance/reviews/",
        AdminParticipantComplianceReviewListView.as_view(),
        name="admin-participant-compliance-reviews",
    ),
    path(
        "markets/portfolio/activity/",
        MarketPortfolioActivityListView.as_view(),
        name="market-portfolio-activity-list",
    ),
    path(
        "markets/portfolio/positions/",
        MarketPortfolioPositionListView.as_view(),
        name="market-portfolio-position-list",
    ),
    path(
        "markets/portfolio/summary/",
        MarketPortfolioSummaryView.as_view(),
        name="market-portfolio-summary",
    ),
    path(
        "markets/orders/open/",
        ParticipantOpenOrderListView.as_view(),
        name="participant-open-orders",
    ),
    path(
        "market-positions/",
        MarketPositionListView.as_view(),
        name="market-position-list",
    ),
    path(
        "market-positions/<uuid:position_id>/",
        MarketPositionDetailView.as_view(),
        name="market-position-detail",
    ),
    path(
        "market-orders/",
        MarketOrderListView.as_view(),
        name="market-order-list",
    ),
    path(
        "market-orders/<uuid:order_id>/",
        MarketOrderDetailView.as_view(),
        name="market-order-detail",
    ),
    path(
        "market-orders/<uuid:order_id>/cancel/",
        MarketOrderCancelView.as_view(),
        name="market-order-cancel",
    ),
    path(
        "markets/<uuid:market_id>/orders/",
        MarketOrderCreateView.as_view(),
        name="market-order-create",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/result-dispute-decisions/"),
        AdminMarketResultDisputeDecisionCreateView.as_view(),
        name=("admin-market-result-dispute-decision-create"),
    ),
    path(
        ("market-admin/result-dispute-decisions/" "<uuid:decision_id>/"),
        AdminMarketResultDisputeDecisionDetailView.as_view(),
        name=("admin-market-result-dispute-decision-detail"),
    ),
    path(
        "market-admin/result-disputes/",
        AdminMarketResultDisputeListView.as_view(),
        name="admin-market-result-dispute-list",
    ),
    path(
        "market-admin/result-disputes/<uuid:dispute_id>/",
        AdminMarketResultDisputeDetailView.as_view(),
        name="admin-market-result-dispute-detail",
    ),
    path(
        "market-admin/markets/",
        MarketAdminListCreateView.as_view(),
        name="admin-market-list",
    ),
    path(
        "market-admin/markets/<uuid:market_id>/",
        MarketAdminDetailView.as_view(),
        name="admin-market-detail",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/submit/"),
        MarketSubmitView.as_view(),
        name="admin-market-submit",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/approve/"),
        MarketApproveView.as_view(),
        name="admin-market-approve",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/reject/"),
        MarketRejectView.as_view(),
        name="admin-market-reject",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/open/"),
        MarketOpenView.as_view(),
        name="admin-market-open",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/suspend/"),
        MarketSuspendView.as_view(),
        name="admin-market-suspend",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/reopen/"),
        MarketReopenView.as_view(),
        name="admin-market-reopen",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/close/"),
        MarketCloseView.as_view(),
        name="admin-market-close",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/provisional-result/"),
        MarketProvisionalResultPublishView.as_view(),
        name="market-provisional-result-publish",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/resolve/"),
        MarketResolveView.as_view(),
        name="admin-market-resolve",
    ),
    path(
        ("market-admin/markets/" "<uuid:market_id>/void/"),
        MarketVoidView.as_view(),
        name="admin-market-void",
    ),
    path(
        "markets/categories/",
        MarketCategoryListView.as_view(),
        name="category-list",
    ),
    path(
        "markets/stats/",
        MarketStatsView.as_view(),
        name="market-stats",
    ),
    path(
        "markets/",
        MarketListView.as_view(),
        name="market-list",
    ),
    path(
        "markets/<uuid:market_id>/",
        MarketDetailView.as_view(),
        name="market-detail",
    ),
    path(
        "markets/<uuid:market_id>/provisional-result/",
        MarketProvisionalResultDetailView.as_view(),
        name="market-provisional-result-detail",
    ),
    path(
        "markets/<uuid:market_id>/result-disputes/",
        MarketResultDisputeSubmitView.as_view(),
        name="market-result-dispute-submit",
    ),
    path(
        ("markets/<uuid:market_id>/" "result-dispute-decisions/"),
        MarketResultDisputeDecisionListView.as_view(),
        name="market-result-dispute-decision-list",
    ),
    path(
        "markets/<uuid:market_id>/settle/",
        MarketSettlementView.as_view(),
        name="market-settle",
    ),
    path(
        "markets/<uuid:market_id>/void-refund/",
        MarketVoidRefundView.as_view(),
        name="market-void-refund",
    ),
    path(
        "markets/<uuid:market_id>/outcomes/<uuid:outcome_id>/order-book/",
        MarketOrderBookView.as_view(),
        name="market-order-book",
    ),
    path(
        "markets/<uuid:market_id>/outcomes/<uuid:outcome_id>/price-history/",
        MarketOutcomePriceHistoryView.as_view(),
        name="market-outcome-price-history",
    ),
    path(
        "market-result-disputes/",
        ParticipantMarketResultDisputeListView.as_view(),
        name="participant-market-result-dispute-list",
    ),
    path(
        "market-result-disputes/<uuid:dispute_id>/",
        ParticipantMarketResultDisputeDetailView.as_view(),
        name="participant-market-result-dispute-detail",
    ),
    path(
        "market-fills/",
        MarketFillListView.as_view(),
        name="market-fill-list",
    ),
    path(
        "market-fills/<uuid:fill_id>/",
        MarketFillDetailView.as_view(),
        name="market-fill-detail",
    ),
]
