# Generated by Django 5.2.17 on 2026-08-12 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discovery", "0002_postgres_gin_indexes"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FantasyCompetition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "registration_state",
                    models.CharField(
                        choices=[("CLOSED", "Closed"), ("OPEN", "Open")],
                        default="CLOSED",
                        max_length=12,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        default="PUBLIC",
                        max_length=12,
                    ),
                ),
                ("squad_size", models.PositiveSmallIntegerField()),
                ("starting_lineup_size", models.PositiveSmallIntegerField()),
                ("bench_size", models.PositiveSmallIntegerField()),
                ("initial_budget", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_players_per_team", models.PositiveSmallIntegerField(default=3)),
                (
                    "captain_multiplier",
                    models.DecimalField(decimal_places=2, default=2, max_digits=4),
                ),
                ("vice_captain_fallback", models.BooleanField(default=True)),
                ("free_transfers_per_gameweek", models.PositiveSmallIntegerField(default=1)),
                ("transfer_penalty", models.IntegerField(default=4)),
                ("position_rules", models.JSONField(default=dict)),
                ("formation_rules", models.JSONField(default=dict)),
                ("tie_break_rules", models.JSONField(default=list)),
                ("gameweek_rules", models.JSONField(default=dict)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("prize_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fantasy_competitions",
                        to="sports.competition",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fantasy_competitions",
                        to="discovery.season",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FantasyGameweek",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("starts_at", models.DateTimeField()),
                ("deadline_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("LOCKED", "Locked"),
                            ("LIVE", "Live"),
                            ("SCORING", "Scoring"),
                            ("FINALIZED", "Finalized"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameweeks",
                        to="fantasy.fantasycompetition",
                    ),
                ),
                (
                    "fixtures",
                    models.ManyToManyField(
                        blank=True, related_name="fantasy_gameweeks", to="sports.sportingevent"
                    ),
                ),
            ],
            options={
                "ordering": ["fantasy_competition", "number"],
            },
        ),
        migrations.CreateModel(
            name="FantasyLeague",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        default="PRIVATE",
                        max_length=12,
                    ),
                ),
                ("join_code", models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leagues",
                        to="fantasy.fantasycompetition",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_fantasy_leagues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FantasyPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("eligible", models.BooleanField(default=True)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DOUBTFUL", "Doubtful"),
                            ("INJURED", "Injured"),
                            ("SUSPENDED", "Suspended"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_pool",
                        to="fantasy.fantasycompetition",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        limit_choices_to={"kind": "ATHLETE"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fantasy_entries",
                        to="sports.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "player__name"],
            },
        ),
        migrations.CreateModel(
            name="FantasyPlayerGameweekPoints",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_points", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "correction_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_points", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("breakdown", models.JSONField(default=list)),
                ("statistics_available", models.BooleanField(default=False)),
                (
                    "fantasy_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gameweek_points",
                        to="fantasy.fantasyplayer",
                    ),
                ),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_points",
                        to="fantasy.fantasygameweek",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FantasyScoringCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fantasy_scoring_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_points",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="fantasy.fantasyplayergameweekpoints",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FantasyScoringRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statistic_type", models.CharField(max_length=50)),
                ("points", models.DecimalField(decimal_places=2, max_digits=8)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_rules",
                        to="fantasy.fantasycompetition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FantasyTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("budget_remaining", models.DecimalField(decimal_places=2, max_digits=12)),
                ("free_transfers", models.PositiveSmallIntegerField(default=0)),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="fantasy.fantasycompetition",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fantasy_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FantasyLeagueMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="fantasy.fantasyleague",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_memberships",
                        to="fantasy.fantasyteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FantasyTeamGameweekScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("player_points", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("captain_bonus", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "transfer_penalty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_points", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("breakdown", models.JSONField(default=list)),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_scores",
                        to="fantasy.fantasygameweek",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameweek_scores",
                        to="fantasy.fantasyteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FantasyTeamPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_starter", models.BooleanField(default=False)),
                ("bench_order", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_captain", models.BooleanField(default=False)),
                ("is_vice_captain", models.BooleanField(default=False)),
                ("purchase_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fantasy_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_selections",
                        to="fantasy.fantasyplayer",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="fantasy.fantasyteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FantasyTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price_out", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_in", models.DecimalField(decimal_places=2, max_digits=10)),
                ("penalty_points", models.IntegerField(default=0)),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="fantasy.fantasygameweek",
                    ),
                ),
                (
                    "player_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="fantasy.fantasyplayer",
                    ),
                ),
                (
                    "player_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="fantasy.fantasyplayer",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="fantasy.fantasyteam",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="fantasycompetition",
            constraint=models.UniqueConstraint(
                fields=("competition", "season"), name="unique_fantasy_competition_season"
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasygameweek",
            constraint=models.UniqueConstraint(
                fields=("fantasy_competition", "number"), name="unique_fantasy_gameweek_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyplayer",
            constraint=models.UniqueConstraint(
                fields=("fantasy_competition", "player"), name="unique_fantasy_player_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyplayergameweekpoints",
            constraint=models.UniqueConstraint(
                fields=("gameweek", "fantasy_player"), name="unique_fantasy_player_gameweek_points"
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyscoringrule",
            constraint=models.UniqueConstraint(
                fields=("fantasy_competition", "statistic_type", "conditions"),
                name="unique_fantasy_scoring_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyteam",
            constraint=models.UniqueConstraint(
                fields=("owner", "fantasy_competition"),
                name="one_fantasy_team_per_owner_competition",
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyleaguemembership",
            constraint=models.UniqueConstraint(
                fields=("league", "team"), name="unique_fantasy_league_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyteamgameweekscore",
            constraint=models.UniqueConstraint(
                fields=("team", "gameweek"), name="unique_fantasy_team_gameweek_score"
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyteamplayer",
            constraint=models.UniqueConstraint(
                fields=("team", "fantasy_player"), name="unique_player_per_fantasy_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyteamplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True)),
                fields=("team",),
                name="one_captain_per_fantasy_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="fantasyteamplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_vice_captain", True)),
                fields=("team",),
                name="one_vice_captain_per_fantasy_team",
            ),
        ),
    ]
