# Generated by Django 5.2.17 on 2026-08-12 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0002_fantasy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="FantasyTeamGameweekState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("free_transfers_allocated", models.PositiveSmallIntegerField(default=0)),
                ("free_transfers_used", models.PositiveSmallIntegerField(default=0)),
                ("transfer_penalty", models.PositiveIntegerField(default=0)),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_states",
                        to="fantasy.fantasygameweek",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameweek_states",
                        to="fantasy.fantasyteam",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "gameweek"), name="unique_fantasy_team_gameweek_state"
                    )
                ],
            },
        ),
    ]
