# Generated by Django 5.2.17 on 2026-08-18 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_fantasyteamgameweekstate'),
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyStatisticReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved')], db_index=True, default='PENDING', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fantasy_statistic_approvals', to=settings.AUTH_USER_MODEL)),
                ('fantasy_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_reviews', to='fantasy.fantasycompetition')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_statistic_reviews', to='sports.sportingevent')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fantasy_statistic_reviews', to='sports.participant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('fantasy_competition', 'fixture', 'participant'), name='unique_fantasy_statistic_review')],
            },
        ),
    ]
