# Generated by Django 5.2.17 on 2026-08-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_add_starting_points_to_fantasyplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyscoringrule',
            name='rule_type',
            field=models.CharField(choices=[('PER_UNIT', 'Per unit'), ('FLAT', 'Flat'), ('BRACKET', 'Bracket'), ('PER_N', 'Per N units'), ('POSITION', 'Position-based')], default='PER_UNIT', max_length=20),
        ),
    ]
