# Generated by Django 5.2.14 on 2026-08-02 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("route", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "cache_timeout",
                    models.IntegerField(default=300, help_text="Cache timeout in seconds"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "enabled", "display_order"],
                        name="dashboard_d_is_acti_279ede_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=100)),
                ("widget", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("VIEWED", "Dashboard viewed"),
                            ("WIDGET_CLICKED", "Widget clicked"),
                            ("NAVIGATION_CLICKED", "Navigation clicked"),
                            ("MODULE_OPENED", "Module opened"),
                            ("WIDGET_REORDERED", "Widget reordered"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "interaction_type", "-timestamp"],
                        name="dashboard_d_user_id_ba5454_idx",
                    ),
                    models.Index(
                        fields=["user", "module", "-timestamp"],
                        name="dashboard_d_user_id_9d8afe_idx",
                    ),
                    models.Index(fields=["-timestamp"], name="dashboard_d_timesta_8a7195_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardUserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "widget_order",
                    models.JSONField(
                        blank=True, default=list, help_text="Ordered list of widget codes"
                    ),
                ),
                (
                    "hidden_widgets",
                    models.JSONField(
                        blank=True, default=list, help_text="List of hidden widget codes"
                    ),
                ),
                (
                    "layout_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Layout configuration (grid positions, sizes, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user"], name="dashboard_d_user_id_7a0373_idx")],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                (
                    "permission_required",
                    models.CharField(
                        blank=True,
                        help_text="Optional permission required to view this widget",
                        max_length=100,
                    ),
                ),
                (
                    "cache_timeout",
                    models.IntegerField(
                        default=300, help_text="Widget-specific cache timeout in seconds"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboard.dashboardmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["module__display_order", "display_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["module", "is_active", "display_order"],
                        name="dashboard_d_module__6efb55_idx",
                    ),
                    models.Index(fields=["code", "is_active"], name="dashboard_d_code_42993b_idx"),
                ],
                "unique_together": {("module", "code")},
            },
        ),
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("route", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                (
                    "permission_required",
                    models.CharField(
                        blank=True,
                        help_text="Optional permission required to view this menu item",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dashboard.navigationmenu",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["parent", "is_active", "display_order"],
                        name="dashboard_n_parent__2d4faa_idx",
                    ),
                    models.Index(
                        fields=["is_active", "display_order"], name="dashboard_n_is_acti_0ed640_idx"
                    ),
                ],
            },
        ),
    ]
