# Generated by Django 5.2.14 on 2026-07-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_failed_attempts_user_last_failed_attempt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_REGISTERED", "User registered"),
                    ("VERIFICATION_EMAIL_SENT", "Verification email sent"),
                    ("OTP_VERIFIED", "OTP verified"),
                    ("ACCOUNT_ACTIVATED", "Account activated"),
                    ("OTP_RESENT", "OTP resent"),
                    ("FAILED_VERIFICATION", "Failed verification"),
                    ("PASSWORD_RESET_REQUESTED", "Password reset requested"),
                    ("PASSWORD_RESET_EMAIL_SENT", "Password reset email sent"),
                    ("PASSWORD_RESET_VERIFIED", "Password reset verified"),
                    ("PASSWORD_RESET_SUCCESS", "Password reset successful"),
                    ("PASSWORD_RESET_FAILED", "Password reset failed"),
                    ("PASSWORD_RESET_EXPIRED", "Password reset token expired"),
                    ("PASSWORD_RESET_TOKEN_REUSED", "Password reset token reused"),
                    ("ALL_SESSIONS_TERMINATED", "All sessions terminated"),
                ],
                max_length=40,
            ),
        ),
    ]
