# Generated by Django 5.2.16 on 2026-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_REGISTERED", "User registered"),
                    ("VERIFICATION_EMAIL_SENT", "Verification email sent"),
                    ("OTP_VERIFIED", "OTP verified"),
                    ("ACCOUNT_ACTIVATED", "Account activated"),
                    ("OTP_RESENT", "OTP resent"),
                    ("FAILED_VERIFICATION", "Failed verification"),
                    ("EMAIL_VERIFICATION_REQUESTED", "Email verification requested"),
                    ("EMAIL_VERIFICATION_SENT", "Email verification sent"),
                    ("EMAIL_VERIFICATION_RESENT", "Email verification resent"),
                    ("EMAIL_VERIFICATION_SUCCESS", "Email verification success"),
                    ("EMAIL_VERIFICATION_FAILED", "Email verification failed"),
                    ("EMAIL_VERIFICATION_EXPIRED", "Email verification expired"),
                    ("PASSWORD_RESET_REQUESTED", "Password reset requested"),
                    ("PASSWORD_RESET_EMAIL_SENT", "Password reset email sent"),
                    ("PASSWORD_RESET_VERIFIED", "Password reset verified"),
                    ("PASSWORD_RESET_SUCCESS", "Password reset successful"),
                    ("PASSWORD_RESET_FAILED", "Password reset failed"),
                    ("PASSWORD_RESET_EXPIRED", "Password reset token expired"),
                    ("PASSWORD_RESET_TOKEN_REUSED", "Password reset token reused"),
                    ("ALL_SESSIONS_TERMINATED", "All sessions terminated"),
                    ("PROFILE_VIEWED", "Profile viewed"),
                    ("PROFILE_UPDATED", "Profile updated"),
                    ("FAVOURITE_CLUB_UPDATED", "Favourite club updated"),
                    ("AVATAR_UPLOADED", "Avatar uploaded"),
                    ("AVATAR_UPDATED", "Avatar updated"),
                    ("AVATAR_DELETED", "Avatar deleted"),
                    ("UPLOAD_FAILED", "Upload failed"),
                    ("ONBOARDING_STARTED", "Onboarding started"),
                    ("COUNTRY_SELECTED", "Country selected"),
                    ("SPORT_SELECTED", "Sport selected"),
                    ("COMPETITION_SELECTED", "Competition selected"),
                    ("CLUB_SELECTED", "Club selected"),
                    ("STEP_SKIPPED", "Onboarding step skipped"),
                    ("ONBOARDING_RESUMED", "Onboarding resumed"),
                    ("ONBOARDING_COMPLETED", "Onboarding completed"),
                    ("PREFERENCES_UPDATED", "Preferences updated"),
                    ("DASHBOARD_CONFIGURATION_GENERATED", "Dashboard configuration generated"),
                    ("MARKET_ORDER_BLOCKED", "Market order blocked"),
                ],
                max_length=40,
            ),
        ),
    ]
