# Generated by Django 5.2.7 on 2026-08-05 08:08

from collections import defaultdict

import django.db.models.functions.text
import phonenumbers
from django.db import migrations, models


def _mask_phone(value):
    value = str(value or "")
    if len(value) <= 4:
        return "*" * len(value)
    return f"{'*' * (len(value) - 4)}{value[-4:]}"


def _normalize_phone(value):
    try:
        parsed = phonenumbers.parse(str(value).strip(), None)
    except phonenumbers.NumberParseException as exc:
        raise ValueError("invalid international phone number") from exc
    if not phonenumbers.is_valid_number(parsed):
        raise ValueError("invalid international phone number")
    return phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.E164)


def fail_on_unsafe_identity_data(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    rows = User.objects.using(schema_editor.connection.alias).values(
        "id", "email", "username", "phone_number"
    )
    emails = defaultdict(list)
    usernames = defaultdict(list)
    phones = defaultdict(list)
    invalid_phones = []
    noncanonical_phones = []
    blank_phone_strings = []
    blank_emails = []
    blank_usernames = []

    for row in rows:
        record_id = str(row["id"])
        email = row["email"]
        username = row["username"]
        phone = row["phone_number"]

        if email is None or not str(email).strip():
            blank_emails.append(record_id)
        else:
            emails[str(email).strip().casefold()].append(record_id)
        if username is None or not str(username).strip():
            blank_usernames.append(record_id)
        else:
            usernames[str(username).strip().casefold()].append(record_id)

        if phone is None:
            continue
        if not str(phone).strip():
            blank_phone_strings.append(record_id)
            continue
        try:
            normalized = _normalize_phone(phone)
        except ValueError:
            invalid_phones.append({"id": record_id, "phone": _mask_phone(phone)})
            continue
        phones[normalized].append(record_id)
        if str(phone).strip() != normalized:
            noncanonical_phones.append(
                {
                    "id": record_id,
                    "phone": _mask_phone(phone),
                    "canonical": _mask_phone(normalized),
                }
            )

    email_collisions = [ids for ids in emails.values() if len(ids) > 1]
    username_collisions = [ids for ids in usernames.values() if len(ids) > 1]
    phone_collisions = [
        {"phone": _mask_phone(phone), "ids": ids} for phone, ids in phones.items() if len(ids) > 1
    ]
    details = []
    if email_collisions:
        details.append(f"email collisions ids={email_collisions}")
    if username_collisions:
        details.append(f"username collisions ids={username_collisions}")
    if phone_collisions:
        details.append(f"phone collisions={phone_collisions}")
    if invalid_phones:
        details.append(f"invalid phones={invalid_phones}")
    if noncanonical_phones:
        details.append(f"noncanonical phones={noncanonical_phones}")
    if blank_phone_strings:
        details.append(f"blank phone string ids={blank_phone_strings}")
    if blank_emails:
        details.append(f"blank/NULL email ids={blank_emails}")
    if blank_usernames:
        details.append(f"blank/NULL username ids={blank_usernames}")
    if not details:
        return
    raise RuntimeError(
        "Migration 0008 stopped before schema changes. Resolve identity data using an "
        "approved policy and run `python manage.py audit_identity_collisions`: "
        + "; ".join(details)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_auditlog_action"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(fail_on_unsafe_identity_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="accounts_user_email_ci_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="accounts_user_username_ci_unique",
            ),
        ),
    ]
