# Generated by Django 5.2.17 on 2026-08-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_accountsetuptoken_userpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="permission",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="delegatable",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="scope",
            field=models.CharField(
                choices=[("PLATFORM", "Platform"), ("CLUB", "Club")],
                db_index=True,
                default="PLATFORM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="role",
            name="scope",
            field=models.CharField(
                choices=[("PLATFORM", "Platform"), ("CLUB", "Club")],
                db_index=True,
                default="PLATFORM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["scope", "active", "delegatable"], name="authenticat_scope_05c2a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["scope", "is_system"], name="authenticat_scope_46ed00_idx"),
        ),
    ]
