# Generated by Django 5.2.14 on 2026-08-04 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_wallet_ledger_foundation"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ledgerentry",
            name="wallets_led_created_abc123_idx",
        ),
        migrations.RemoveIndex(
            model_name="wallet",
            name="wallets_wal_user_id_5f9113_idx",
        ),
        migrations.RenameIndex(
            model_name="wallettransaction",
            new_name="wallets_wal_wallet__6d3ee8_idx",
            old_name="wallets_txn_wallet__abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="wallettransaction",
            new_name="wallets_wal_transac_d6c260_idx",
            old_name="wallets_txn_type_abc123_idx",
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="provider_reference",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="depositintent",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_intent",
                to="wallets.wallettransaction",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="wallets.wallettransaction",
            ),
        ),
        migrations.AlterField(
            model_name="paymentprovider",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Provider-specific configuration"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="destination",
            field=models.JSONField(
                help_text="Provider-specific destination details, e.g., bank account"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawal_request",
                to="wallets.wallettransaction",
            ),
        ),
    ]
