# Generated by Django 5.2.14 on 2026-08-05 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0021_remove_marketfeeschedule_mkt_fee_scope_version_uniq_and_more"),
        ("wallets", "0002_remove_ledgerentry_wallets_led_created_abc123_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="available_balance_after",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="available_balance_before",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("RESERVE", "Reserve"),
                    ("RELEASE", "Release"),
                ],
                db_index=True,
                default="CREDIT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="fill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="markets.marketfill",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="idempotency_reference",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="market",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="markets.market",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="markets.marketorder",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="reserved_balance_after",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="reserved_balance_before",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="wallets.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="wallets.wallettransaction",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(db_index=True, default="UGX", max_length=3),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_reference__isnull", False)),
                fields=("idempotency_reference",),
                name="unique_idempotency_reference",
            ),
        ),
    ]
