# Generated by Django 5.2.14 on 2026-08-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0021_remove_marketfeeschedule_mkt_fee_scope_version_uniq_and_more"),
        ("wallets", "0003_ledgerentry_available_balance_after_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ledger_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_balance_before__gte", 0)),
                name="ledger_available_before_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_balance_after__gte", 0)),
                name="ledger_available_after_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_balance_before__gte", 0)),
                name="ledger_reserved_before_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_balance_after__gte", 0)),
                name="ledger_reserved_after_non_negative",
            ),
        ),
    ]
