# Generated by Django 5.2.17 on 2026-08-15 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_ledgerentry_ledger_amount_positive_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PesapalDeposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "environment",
                    models.CharField(
                        choices=[("SANDBOX", "Sandbox"), ("LIVE", "Live")],
                        db_index=True,
                        default="SANDBOX",
                        max_length=10,
                    ),
                ),
                ("merchant_reference", models.CharField(db_index=True, max_length=50, unique=True)),
                ("order_tracking_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("redirect_url", models.URLField(blank=True, max_length=2048)),
                ("provider_status", models.CharField(blank=True, db_index=True, max_length=30)),
                ("confirmation_code", models.CharField(blank=True, max_length=255)),
                ("payment_method", models.CharField(blank=True, max_length=100)),
                ("payment_account", models.CharField(blank=True, max_length=255)),
                ("status_description", models.TextField(blank=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pesapal",
                        to="wallets.depositintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("order_tracking_id", ""), _negated=True),
                        fields=("order_tracking_id",),
                        name="unique_pesapal_order_tracking_id",
                    )
                ],
            },
        ),
    ]
