# Generated by Django 5.2.17 on 2026-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_pesapal_sandbox_deposits"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="approval_mode",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("AUTOMATIC", "Automatic"), ("MANUAL", "Manual")],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="approval_policy_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="risk_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
