# Generated by Django 5.2.17 on 2026-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0008_withdrawal_failure_reason_and_processing_audit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("SETTLEMENT_PAYOUT", "Settlement payout"),
                    ("VOID_REFUND", "Void refund"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
