# Generated by Django 5.2.14 on 2026-08-06 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discovery", "0002_postgres_gin_indexes"),
        ("profiles", "0002_club_competition_club_sport_and_more"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video"), ("DOCUMENT", "Document")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="clubs/media/")),
                ("url", models.URLField(blank=True, max_length=1024)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="clubs/thumbnails/"),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("display_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="profiles.club",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_club_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_club_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubNews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=320)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="club_news",
                        to="discovery.newscategory",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_news",
                        to="profiles.club",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_cover",
                        to="clubs.clubmedia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_club_news",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_club_news",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_news",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubProfileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("version", models.PositiveIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("founded", models.PositiveIntegerField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="clubs/logos/")),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="clubs/covers/"),
                ),
                ("stadium", models.CharField(blank=True, max_length=255)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("coach", models.CharField(blank=True, max_length=180)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_versions",
                        to="profiles.club",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_profile_versions",
                        to="profiles.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_club_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_profile_versions",
                        to="sports.competition",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_club_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ClubWorkspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Club Admin"), ("STAFF", "Club Staff")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_reason", models.TextField(blank=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="profiles.club",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "billing_period",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                            ("ONE_TIME", "One time"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("duration_days", models.PositiveIntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("max_members", models.PositiveIntegerField(blank=True, null=True)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_plans",
                        to="profiles.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_membership_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_membership_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("PENDING", "Pending"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="clubs.membershipplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchandiseProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("sku", models.CharField(blank=True, db_index=True, max_length=100)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("reserved_stock", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                ("images", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                            ("OUT_OF_STOCK", "Out of stock"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchandise_products",
                        to="profiles.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_merchandise",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_merchandise",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "Restock"),
                            ("SALE", "Sale"),
                            ("RETURN", "Return"),
                            ("DAMAGED", "Damaged"),
                            ("CORRECTION", "Correction"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("quantity_change", models.IntegerField()),
                ("previous_stock", models.PositiveIntegerField()),
                ("new_stock", models.PositiveIntegerField()),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_adjustments",
                        to="clubs.merchandiseproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_categories",
                        to="profiles.club",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="merchandiseproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="clubs.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="StaffInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Club Admin"), ("STAFF", "Club Staff")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_staff_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_invitations",
                        to="profiles.club",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_staff_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PROCESSING", "Processing"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("shipping_address", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_orders",
                        to="profiles.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="clubs.storeorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="clubs.merchandiseproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TicketProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("sales_start", models.DateTimeField(blank=True, null=True)),
                ("sales_end", models.DateTimeField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("sold", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                            ("SOLD_OUT", "Sold out"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_refundable", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_products",
                        to="profiles.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ticket_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_products",
                        to="sports.sportingevent",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_ticket_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="clubs.ticketproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("FAN_GROWTH", "Fan growth"),
                            ("MEMBERSHIP_SALES", "Membership sales"),
                            ("TICKET_SALES", "Ticket sales"),
                            ("MERCHANDISE_SALES", "Merchandise sales"),
                            ("CONTENT_ENGAGEMENT", "Content engagement"),
                            ("REVENUE", "Revenue"),
                            ("INVENTORY_PERFORMANCE", "Inventory performance"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="profiles.club",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "metric_type"],
                "indexes": [
                    models.Index(
                        fields=["club", "metric_type", "-date"],
                        name="clubs_cluba_club_id_227cf2_idx",
                    ),
                    models.Index(
                        fields=["metric_type", "-date"], name="clubs_cluba_metric__cb4b6b_idx"
                    ),
                ],
                "unique_together": {("club", "metric_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="ClubAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("WORKSPACE_SWITCHED", "Workspace switched"),
                            ("CLUB_PROFILE_UPDATED", "Club profile updated"),
                            ("BRANDING_CHANGED", "Branding changed"),
                            ("MEDIA_UPLOADED", "Media uploaded"),
                            ("NEWS_PUBLISHED", "News published"),
                            ("MEMBERSHIP_CREATED", "Membership created"),
                            ("TICKET_CREATED", "Ticket created"),
                            ("PRODUCT_CREATED", "Product created"),
                            ("INVENTORY_UPDATED", "Inventory updated"),
                            ("STAFF_INVITED", "Staff invited"),
                            ("STAFF_DISABLED", "Staff disabled"),
                            ("ROLE_GRANTED", "Role granted"),
                            ("ROLE_REVOKED", "Role revoked"),
                            ("PERMISSION_CHANGED", "Permission changed"),
                            ("ANALYTICS_VIEWED", "Analytics viewed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, db_index=True, max_length=50)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="profiles.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "action", "-created_at"],
                        name="clubs_cluba_club_id_6698b1_idx",
                    ),
                    models.Index(
                        fields=["user", "action", "-created_at"],
                        name="clubs_cluba_user_id_44fb4e_idx",
                    ),
                    models.Index(fields=["-created_at"], name="clubs_cluba_created_ab2301_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="clubmedia",
            index=models.Index(
                fields=["club", "status", "display_order"], name="clubs_clubm_club_id_55823b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clubmedia",
            index=models.Index(
                fields=["club", "media_type", "status"], name="clubs_clubm_club_id_d14f42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clubmedia",
            index=models.Index(
                fields=["is_featured", "status"], name="clubs_clubm_is_feat_4c87a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clubnews",
            index=models.Index(
                fields=["club", "status", "-published_at"], name="clubs_clubn_club_id_049b19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clubnews",
            index=models.Index(
                fields=["status", "is_verified", "-published_at"],
                name="clubs_clubn_status_2e2bd2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clubnews",
            index=models.Index(
                fields=["is_featured", "status", "-published_at"],
                name="clubs_clubn_is_feat_9ff2d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clubprofileversion",
            index=models.Index(
                fields=["club", "status", "-version"], name="clubs_clubp_club_id_312cd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clubprofileversion",
            index=models.Index(
                fields=["status", "-created_at"], name="clubs_clubp_status_4d26c4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clubprofileversion",
            unique_together={("club", "version")},
        ),
        migrations.AddIndex(
            model_name="clubworkspace",
            index=models.Index(
                fields=["club", "is_active", "role"], name="clubs_clubw_club_id_e72255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clubworkspace",
            index=models.Index(fields=["user", "is_active"], name="clubs_clubw_user_id_f2a813_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="clubworkspace",
            unique_together={("user", "club")},
        ),
        migrations.AddIndex(
            model_name="membershipplan",
            index=models.Index(
                fields=["club", "status", "-created_at"], name="clubs_membe_club_id_33b02c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipplan",
            index=models.Index(
                fields=["status", "is_featured"], name="clubs_membe_status_3a0800_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membershipplan",
            unique_together={("club", "slug")},
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "status", "-starts_at"], name="clubs_membe_user_id_31f575_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["plan", "status"], name="clubs_membe_plan_id_9021b1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "plan")},
        ),
        migrations.AddIndex(
            model_name="inventoryadjustment",
            index=models.Index(
                fields=["product", "-created_at"], name="clubs_inven_product_d21a9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryadjustment",
            index=models.Index(
                fields=["adjustment_type", "-created_at"], name="clubs_inven_adjustm_261bfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["club", "is_active", "display_order"], name="clubs_produ_club_id_e1a036_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together={("club", "slug")},
        ),
        migrations.AddIndex(
            model_name="merchandiseproduct",
            index=models.Index(
                fields=["club", "status", "-created_at"], name="clubs_merch_club_id_6e89d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchandiseproduct",
            index=models.Index(
                fields=["status", "is_featured"], name="clubs_merch_status_5607d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchandiseproduct",
            index=models.Index(fields=["sku", "status"], name="clubs_merch_sku_72c6f0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="merchandiseproduct",
            unique_together={("club", "slug")},
        ),
        migrations.AddIndex(
            model_name="staffinvitation",
            index=models.Index(
                fields=["club", "status", "-created_at"], name="clubs_staff_club_id_86bbc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffinvitation",
            index=models.Index(fields=["token", "status"], name="clubs_staff_token_ab5c7e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="staffinvitation",
            unique_together={("club", "email", "status")},
        ),
        migrations.AddIndex(
            model_name="storeorder",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="clubs_store_user_id_5186b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeorder",
            index=models.Index(
                fields=["club", "status", "-created_at"], name="clubs_store_club_id_fbd3b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeorderitem",
            index=models.Index(fields=["order", "product"], name="clubs_store_order_i_1943b4_idx"),
        ),
        migrations.AddIndex(
            model_name="ticketproduct",
            index=models.Index(
                fields=["club", "status", "-created_at"], name="clubs_ticke_club_id_57a58e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketproduct",
            index=models.Index(
                fields=["status", "sales_start", "sales_end"], name="clubs_ticke_status_dad663_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticketproduct",
            unique_together={("club", "slug")},
        ),
        migrations.AddIndex(
            model_name="ticketorder",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="clubs_ticke_user_id_e89efc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketorder",
            index=models.Index(fields=["product", "status"], name="clubs_ticke_product_ecaa11_idx"),
        ),
    ]
