# Generated by Django 5.2.17 on 2026-08-10 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Club Admin"), ("STAFF", "Club Staff")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to="clubs.clubworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "is_active", "role"],
                        name="clubs_works_workspa_904e4e_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"], name="clubs_works_user_id_f8a6dd_idx"
                    ),
                ],
                "unique_together": {("user", "workspace")},
            },
        ),
    ]
