# Generated by Django 5.2.14 on 2026-08-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_workspacemembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmedia",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="clubnews",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="clubprofileversion",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
