# Generated by Django 5.2.17 on 2026-09-03 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_alter_clubauditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketorder",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="checked_in_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_in_ticket_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="code",
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="clubauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("WORKSPACE_SWITCHED", "Workspace switched"),
                    ("CLUB_PROFILE_UPDATED", "Club profile updated"),
                    ("BRANDING_CHANGED", "Branding changed"),
                    ("MEDIA_UPLOADED", "Media uploaded"),
                    ("NEWS_PUBLISHED", "News published"),
                    ("NEWS_SUBMITTED", "News submitted for review"),
                    ("MEMBERSHIP_CREATED", "Membership created"),
                    ("TICKET_CREATED", "Ticket created"),
                    ("TICKET_PUBLISHED", "Ticket published"),
                    ("TICKET_ORDER_CREATED", "Ticket order created"),
                    ("TICKET_ORDER_PAID", "Ticket order paid"),
                    ("TICKET_SCANNED", "Ticket scanned"),
                    ("PRODUCT_CREATED", "Product created"),
                    ("INVENTORY_UPDATED", "Inventory updated"),
                    ("STAFF_INVITED", "Staff invited"),
                    ("STAFF_DISABLED", "Staff disabled"),
                    ("ROLE_GRANTED", "Role granted"),
                    ("ROLE_REVOKED", "Role revoked"),
                    ("PERMISSION_CHANGED", "Permission changed"),
                    ("ANALYTICS_VIEWED", "Analytics viewed"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
