# Generated by Django 5.2.17 on 2026-08-19 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_alter_clubauditlog_action"),
        ("profiles", "0003_club_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FIT", "Fit"),
                            ("INJURED", "Injured"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="FIT",
                        max_length=20,
                    ),
                ),
                ("contract_end", models.DateField(blank=True, null=True)),
                ("market_value", models.CharField(blank=True, max_length=100)),
                ("jersey_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("photo", models.CharField(blank=True, max_length=500)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squad_players",
                        to="profiles.club",
                    ),
                ),
            ],
            options={
                "ordering": ["jersey_number", "name"],
                "indexes": [
                    models.Index(fields=["club", "status"], name="clubs_clubp_club_id_0abf40_idx")
                ],
            },
        ),
    ]
