# Generated by Django 5.2.17 on 2026-08-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_alter_clubauditlog_action"),
        ("clubs", "0005_clubplayer"),
    ]

    operations = []
