# Generated by Django 5.2.17 on 2026-09-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_ticketorder_checked_in_at_ticketorder_checked_in_by_and_more"),
        ("clubs", "0006_merge_0005_alter_clubauditlog_action_0005_clubplayer"),
    ]

    operations = []
