# Generated by Django 5.2.17 on 2026-09-04 08:30

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


def normalize_and_validate_skus(apps, schema_editor):
    Product = apps.get_model("clubs", "MerchandiseProduct")
    seen = {}
    for product in Product.objects.exclude(sku="").order_by("club_id", "id"):
        normalized = product.sku.strip().upper()
        key = (product.club_id, normalized.casefold())
        if key in seen:
            raise RuntimeError(
                "Cannot add club SKU uniqueness: products "
                f"{seen[key]} and {product.pk} share normalized SKU {normalized!r}. "
                "Resolve the ambiguous catalogue records and rerun the migration."
            )
        seen[key] = product.pk
        if product.sku != normalized:
            Product.objects.filter(pk=product.pk).update(sku=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_merge_0005_alter_clubauditlog_action_0005_clubplayer"),
        ("profiles", "0003_club_logo"),
        ("wallets", "0008_withdrawal_failure_reason_and_processing_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreOrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PROCESSING", "Processing"),
                            ("READY_FOR_COLLECTION", "Ready for collection"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PROCESSING", "Processing"),
                            ("READY_FOR_COLLECTION", "Ready for collection"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="storeorder",
            name="checkout_group",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="storeorder",
            name="checkout_idempotency_key",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="storeorder",
            name="delivery_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="storeorder",
            name="payment_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store_orders",
                to="wallets.wallettransaction",
            ),
        ),
        migrations.AlterField(
            model_name="storeorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("PROCESSING", "Processing"),
                    ("READY_FOR_COLLECTION", "Ready for collection"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("FULFILLED", "Fulfilled"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_and_validate_skus, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="merchandiseproduct",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("sku"),
                models.F("club"),
                condition=models.Q(("sku", ""), _negated=True),
                name="unique_club_normalized_sku",
            ),
        ),
        migrations.AddConstraint(
            model_name="storeorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("checkout_idempotency_key__isnull", False)),
                fields=("user", "club", "checkout_idempotency_key"),
                name="unique_store_checkout_per_user_club",
            ),
        ),
        migrations.AddField(
            model_name="storeorderstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="storeorderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_history",
                to="clubs.storeorder",
            ),
        ),
    ]
