# Generated by Django 5.2.17 on 2026-09-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_storeorderstatushistory_storeorder_checkout_group_and_more"),
        ("wallets", "0008_withdrawal_failure_reason_and_processing_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeorder",
            name="refund_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunded_store_orders",
                to="wallets.wallettransaction",
            ),
        ),
    ]
