# Generated by Django 5.2.17 on 2026-09-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_merge_20260904_0239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("WORKSPACE_SWITCHED", "Workspace switched"),
                    ("CLUB_PROFILE_UPDATED", "Club profile updated"),
                    ("BRANDING_CHANGED", "Branding changed"),
                    ("MEDIA_UPLOADED", "Media uploaded"),
                    ("NEWS_PUBLISHED", "News published"),
                    ("NEWS_SUBMITTED", "News submitted for review"),
                    ("MEMBERSHIP_CREATED", "Membership created"),
                    ("TICKET_CREATED", "Ticket created"),
                    ("TICKET_PUBLISHED", "Ticket published"),
                    ("TICKET_ORDER_CREATED", "Ticket order created"),
                    ("TICKET_ORDER_PAID", "Ticket order paid"),
                    ("TICKET_SCANNED", "Ticket scanned"),
                    ("PRODUCT_CREATED", "Product created"),
                    ("INVENTORY_UPDATED", "Inventory updated"),
                    ("STAFF_INVITED", "Staff invited"),
                    ("STAFF_DISABLED", "Staff disabled"),
                    ("ROLE_GRANTED", "Role granted"),
                    ("ROLE_REVOKED", "Role revoked"),
                    ("PERMISSION_CHANGED", "Permission changed"),
                    ("ANALYTICS_VIEWED", "Analytics viewed"),
                    ("MATCH_DATA_UPLOADED", "Match data uploaded"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
