# Generated by Django 5.2.14 on 2026-08-01 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("STEP_SELECTED", "Step Selected"),
                            ("STEP_SKIPPED", "Step Skipped"),
                            ("COMPLETED", "Completed"),
                            ("RESUMED", "Resumed"),
                            ("PREFERENCES_UPDATED", "Preferences Updated"),
                            ("DASHBOARD_GENERATED", "Dashboard Generated"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"], name="onboarding__user_id_756a24_idx"
                    ),
                    models.Index(
                        fields=["event_type", "created_at"], name="onboarding__event_t_40561b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserClubPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_preferences",
                        to="profiles.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["club__name"],
                "indexes": [
                    models.Index(fields=["user", "club"], name="onboarding__user_id_5263ea_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "club"), name="unique_user_club_preference"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserCompetitionPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_preferences",
                        to="sports.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["competition__name"],
                "indexes": [
                    models.Index(
                        fields=["user", "competition"], name="onboarding__user_id_d7e9ca_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "competition"), name="unique_user_competition_preference"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserOnboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("COUNTRY", "Select Country"),
                            ("SPORTS", "Select Favourite Sports"),
                            ("COMPETITIONS", "Select Favourite Competitions"),
                            ("CLUBS", "Select Favourite Clubs"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="COUNTRY",
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_steps", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="onboarding__user_id_2cbc45_idx"),
                    models.Index(fields=["completed"], name="onboarding__complet_1999bd_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSportPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_preferences",
                        to="sports.sport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sport_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sport__name"],
                "indexes": [
                    models.Index(fields=["user", "sport"], name="onboarding__user_id_26bd3c_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "sport"), name="unique_user_sport_preference"
                    )
                ],
            },
        ),
    ]
