# Generated by Django 5.2.14 on 2026-08-03 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0002_club_competition_club_sport_and_more"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="discovery_n_is_acti_13c05e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seasons",
                        to="sports.competition",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seasons",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_on", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClubProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="clubs/logos/")),
                ("stadium", models.CharField(blank=True, max_length=255)),
                ("coach", models.CharField(blank=True, max_length=180)),
                ("founded", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="profiles.club",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_profiles",
                        to="profiles.country",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_profiles",
                        to="sports.competition",
                    ),
                ),
                (
                    "current_season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_profiles",
                        to="discovery.season",
                    ),
                ),
            ],
            options={
                "ordering": ["club__name"],
            },
        ),
        migrations.CreateModel(
            name="SportsFeedProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("base_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "code"], name="discovery_s_is_acti_282d11_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SportsFeedIngestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("feed_timestamp", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("records_received", models.PositiveIntegerField(default=0)),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestions",
                        to="discovery.sportsfeedprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("city", models.CharField(blank=True, max_length=180)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="profiles.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MatchCentre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("result", models.CharField(blank=True, max_length=255)),
                ("home_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("attendance", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "data_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Confidence 0.00 - 1.00",
                        max_digits=5,
                    ),
                ),
                (
                    "feed_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "fixture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_centre",
                        to="sports.sportingevent",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_centres",
                        to="discovery.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SEARCH_PERFORMED", "Search performed"),
                            ("SEARCH_FILTER_APPLIED", "Search filter applied"),
                            ("CLUB_VIEWED", "Club viewed"),
                            ("PLAYER_VIEWED", "Player viewed"),
                            ("FIXTURE_VIEWED", "Fixture viewed"),
                            ("MATCH_CENTRE_VIEWED", "Match centre viewed"),
                            ("NEWS_VIEWED", "News viewed"),
                            ("CLUB_FOLLOWED", "Club followed"),
                            ("CLUB_UNFOLLOWED", "Club unfollowed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, db_index=True, max_length=50)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "-timestamp"],
                        name="discovery_a_user_id_c49538_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"], name="discovery_a_action_361341_idx"
                    ),
                    models.Index(fields=["-timestamp"], name="discovery_a_timesta_083135_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchBroadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=180)),
                ("url", models.URLField(blank=True)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                (
                    "match_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="discovery.matchcentre",
                    ),
                ),
            ],
            options={
                "ordering": ["match_centre", "provider"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match_centre", "provider", "country_code"),
                        name="unique_broadcast_per_match",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchLineup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.CharField(choices=[("HOME", "Home"), ("AWAY", "Away")], max_length=10),
                ),
                ("position", models.CharField(blank=True, max_length=100)),
                ("shirt_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_starter", models.BooleanField(db_index=True, default=True)),
                (
                    "match_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="discovery.matchcentre",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_lineups",
                        to="sports.participant",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_lineups",
                        to="sports.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["match_centre", "side", "is_starter", "position"],
                "indexes": [
                    models.Index(
                        fields=["match_centre", "side", "is_starter"],
                        name="discovery_m_match_c_5e9895_idx",
                    ),
                    models.Index(
                        fields=["player", "match_centre"], name="discovery_m_player__54ae10_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchOfficial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=180)),
                (
                    "match_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officials",
                        to="discovery.matchcentre",
                    ),
                ),
            ],
            options={
                "ordering": ["match_centre", "role"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match_centre", "role", "name"), name="unique_official_per_match"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchPlayerStatistic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stat_type", models.CharField(db_index=True, max_length=100)),
                ("value", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "match_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_statistics",
                        to="discovery.matchcentre",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_player_statistics",
                        to="sports.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["match_centre", "stat_type"],
                "indexes": [
                    models.Index(
                        fields=["match_centre", "stat_type"], name="discovery_m_match_c_6ab6ea_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match_centre", "participant", "stat_type"),
                        name="unique_player_stat_per_match",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchTeamStatistic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stat_type", models.CharField(db_index=True, max_length=100)),
                ("value", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "match_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_statistics",
                        to="discovery.matchcentre",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_team_statistics",
                        to="sports.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["match_centre", "stat_type"],
                "indexes": [
                    models.Index(
                        fields=["match_centre", "stat_type"], name="discovery_m_match_c_484c9b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match_centre", "participant", "stat_type"),
                        name="unique_team_stat_per_match",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchTimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("GOAL", "Goal"),
                            ("ASSIST", "Assist"),
                            ("YELLOW_CARD", "Yellow card"),
                            ("RED_CARD", "Red card"),
                            ("SUBSTITUTION", "Substitution"),
                            ("PENALTY", "Penalty"),
                            ("OWN_GOAL", "Own goal"),
                            ("MATCH_START", "Match start"),
                            ("MATCH_END", "Match end"),
                            ("HALF_TIME", "Half time"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("minute", models.PositiveSmallIntegerField(db_index=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "match_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="discovery.matchcentre",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_timeline_events",
                        to="sports.participant",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_timeline_events",
                        to="sports.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["match_centre", "minute"],
                "indexes": [
                    models.Index(
                        fields=["match_centre", "minute"], name="discovery_m_match_c_4f19a5_idx"
                    ),
                    models.Index(
                        fields=["match_centre", "event_type"], name="discovery_m_match_c_6f5fda_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=320, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_articles",
                        to="profiles.club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_articles",
                        to="sports.competition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_news",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_articles",
                        to="sports.participant",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_articles",
                        to="sports.sport",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_articles",
                        to="discovery.newscategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_verified", "published_at"],
                        name="discovery_n_status_d4f8f3_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "status", "published_at"],
                        name="discovery_n_is_feat_5d2f94_idx",
                    ),
                    models.Index(
                        fields=["category", "status", "published_at"],
                        name="discovery_n_categor_69e62c_idx",
                    ),
                    models.Index(
                        fields=["club", "status", "published_at"],
                        name="discovery_n_club_id_a8c4e1_idx",
                    ),
                    models.Index(
                        fields=["competition", "status", "published_at"],
                        name="discovery_n_competi_ce82cf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("shirt_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("biography", models.TextField(blank=True)),
                ("career_history", models.JSONField(blank=True, default=list)),
                ("statistics", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INJURED", "Injured"),
                            ("SUSPENDED", "Suspended"),
                            ("RETIRED", "Retired"),
                            ("TRANSFERRED", "Transferred"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_profiles",
                        to="profiles.club",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_profiles",
                        to="profiles.country",
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to="sports.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["participant__name"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "is_verified"],
                        name="discovery_p_is_publ_36a1a7_idx",
                    ),
                    models.Index(
                        fields=["club", "is_published"], name="discovery_p_club_id_5d5063_idx"
                    ),
                    models.Index(
                        fields=["status", "is_published"], name="discovery_p_status_7e337d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(db_index=True, max_length=300)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("clicked_entity_type", models.CharField(blank=True, max_length=50)),
                ("clicked_entity_id", models.UUIDField(blank=True, null=True)),
                ("applied_filters", models.JSONField(blank=True, default=dict)),
                ("is_empty", models.BooleanField(db_index=True, default=False)),
                ("is_failed", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"], name="discovery_s_user_id_9bba79_idx"
                    ),
                    models.Index(
                        fields=["query", "-timestamp"], name="discovery_s_query_a631cd_idx"
                    ),
                    models.Index(fields=["-timestamp"], name="discovery_s_timesta_c4731a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("RECENT", "Recently searched"),
                            ("POPULAR", "Popular search"),
                            ("TRENDING", "Trending"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.UUIDField(db_index=True)),
                ("display_name", models.CharField(max_length=300)),
                ("score", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
                "indexes": [
                    models.Index(
                        fields=["suggestion_type", "is_active", "-score"],
                        name="discovery_s_suggest_060abc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("suggestion_type", "entity_type", "entity_id", "user"),
                        name="unique_suggestion_identity",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(
                fields=["sport", "is_active"], name="discovery_s_sport_i_e32fb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(
                fields=["competition", "is_active"], name="discovery_s_competi_52a9e3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("sport", "competition", "slug"), name="unique_season_identity"
            ),
        ),
        migrations.AddIndex(
            model_name="clubprofile",
            index=models.Index(
                fields=["is_published", "is_verified"], name="discovery_c_is_publ_70026a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clubprofile",
            index=models.Index(
                fields=["club", "is_published"], name="discovery_c_club_id_c17754_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sportsfeedingestion",
            index=models.Index(
                fields=["provider", "-started_at"], name="discovery_s_provide_3303fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sportsfeedingestion",
            index=models.Index(
                fields=["status", "-started_at"], name="discovery_s_status_1db333_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["is_active", "is_verified"], name="discovery_v_is_acti_5f92d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["country_code", "is_active"], name="discovery_v_country_700cc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchcentre",
            index=models.Index(
                fields=["fixture", "feed_status"], name="discovery_m_fixture_916764_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchcentre",
            index=models.Index(
                fields=["feed_status", "is_verified"], name="discovery_m_feed_st_ba7421_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchcentre",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_confidence__gte", 0), ("data_confidence__lte", 1)),
                name="match_centre_confidence_range",
            ),
        ),
    ]
