# Generated by Django 5.2.17 on 2026-08-16 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0002_postgres_gin_indexes"),
        ("profiles", "0002_club_competition_club_sport_and_more"),
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_trending",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="news",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["is_trending", "status", "published_at"],
                name="discovery_n_is_tren_34a16b_idx",
            ),
        ),
    ]
