# Generated by Django 5.2.17 on 2026-08-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0003_news_is_trending_news_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchcentre",
            name="clock_display",
            field=models.CharField(
                blank=True,
                help_text='Free-text live clock, e.g. "75\'", "HT", "Q3 04:15" — set by admin.',
                max_length=24,
            ),
        ),
    ]
