# Generated by Codex on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0004_matchcentre_clock_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="news",
            name="author",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="news",
            name="avatar",
            field=models.TextField(blank=True),
        ),
    ]
