# Generated by Django 5.2.17 on 2026-08-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_fixtureresultverification'),
        ('discovery', '0005_news_presentation_fields'),
    ]

    operations = [
    ]
