# Generated by Django 5.2.17 on 2026-08-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0003_club_admin_csv_provider"),
        ("discovery", "0005_news_presentation_fields"),
    ]

    operations = []
