# Generated by Django 5.2.17 on 2026-08-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0006_merge_20260818_2139"),
        ("discovery", "0006_merge_20260819_0647"),
    ]

    operations = []
