# Generated by Django 5.2.14 on 2026-08-12 20:07

import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="kycverificationattempt",
            managers=[],
        ),
        migrations.RenameIndex(
            model_name="kycverification",
            new_name="kyc_kycveri_status_df6c85_idx",
            old_name="kyc_kycverif_status_idx",
        ),
        migrations.RenameIndex(
            model_name="kycverification",
            new_name="kyc_kycveri_documen_7ddf31_idx",
            old_name="kyc_kycverif_docnum_idx",
        ),
        migrations.RenameIndex(
            model_name="kycverification",
            new_name="kyc_kycveri_risk_le_ba2f56_idx",
            old_name="kyc_kycverif_risk_idx",
        ),
        migrations.AlterField(
            model_name="kycconfiguration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="kycverificationattempt",
            name="document_image",
            field=models.FileField(upload_to=kyc.models.kyc_private_document_path),
        ),
        migrations.AlterField(
            model_name="kycverificationattempt",
            name="selfie_image",
            field=models.FileField(upload_to=kyc.models.kyc_private_selfie_path),
        ),
    ]
