# Generated by Django 5.2.17 on 2026-08-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0003_alter_kyccheckresult_result_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycverification",
            name="verification_source",
            field=models.CharField(
                choices=[
                    ("PROVIDER", "Provider"),
                    ("MANUAL", "Manual"),
                    ("DEVELOPMENT_BYPASS", "Development bypass"),
                ],
                db_index=True,
                default="PROVIDER",
                max_length=24,
            ),
        ),
    ]
