# Generated by Django 5.2.14 on 2026-08-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0003_alter_kyccheckresult_result_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycverification",
            name="auto_verified",
            field=models.BooleanField(default=False),
        ),
    ]
