# Generated by Django 5.2.17 on 2026-08-15 16:31

import config.storage_backends
import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0005_merge_20260814_kyc_0004_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycverificationattempt",
            name="document_image",
            field=models.FileField(
                storage=config.storage_backends.get_private_storage,
                upload_to=kyc.models.kyc_private_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="kycverificationattempt",
            name="selfie_image",
            field=models.FileField(
                storage=config.storage_backends.get_private_storage,
                upload_to=kyc.models.kyc_private_selfie_path,
            ),
        ),
    ]
