# Generated by Django 5.2.14 on 2026-08-01 18:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("mandatory", models.BooleanField(db_index=True, default=False)),
                ("default_enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(db_index=True, default=0)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="notificatio_is_acti_7864de_idx"
                    ),
                    models.Index(
                        fields=["mandatory", "is_active"], name="notificatio_mandato_b4285f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=100)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="notificatio_is_acti_06926e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunicationConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("MARKETING", "Marketing communications"),
                            ("NEWSLETTER", "Newsletter subscription"),
                            ("SMS_NOTIFICATIONS", "SMS notifications"),
                            ("PUSH_NOTIFICATIONS", "Push notifications"),
                            ("EMAIL_NOTIFICATIONS", "Email notifications"),
                            ("DATA_SHARING", "Data sharing with partners"),
                            ("PROFILING", "User profiling"),
                            ("COOKIES", "Cookie consent"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("granted", models.BooleanField()),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEB", "Web"),
                            ("MOBILE", "Mobile"),
                            ("API", "API"),
                            ("ADMIN", "Admin"),
                        ],
                        default="WEB",
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type", "-granted_at"],
                        name="notificatio_user_id_85551f_idx",
                    ),
                    models.Index(fields=["user", "granted"], name="notificatio_user_id_269ee2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannelCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("capability", models.CharField(db_index=True, max_length=100)),
                ("is_supported", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="notifications.notificationchannel",
                    ),
                ),
            ],
            options={
                "ordering": ["channel__display_order", "capability"],
                "indexes": [
                    models.Index(
                        fields=["channel", "capability"], name="notificatio_channel_d8f285_idx"
                    )
                ],
                "unique_together": {("channel", "capability")},
            },
        ),
        migrations.CreateModel(
            name="NotificationPreferenceAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("NOTIFICATION_PREFERENCES_VIEWED", "Notification preferences viewed"),
                            (
                                "NOTIFICATION_PREFERENCES_UPDATED",
                                "Notification preferences updated",
                            ),
                            ("CHANNEL_ENABLED", "Channel enabled"),
                            ("CHANNEL_DISABLED", "Channel disabled"),
                            ("QUIET_HOURS_UPDATED", "Quiet hours updated"),
                            ("QUIET_HOURS_DISABLED", "Quiet hours disabled"),
                            ("CONSENT_GRANTED", "Consent granted"),
                            ("CONSENT_WITHDRAWN", "Consent withdrawn"),
                            ("RESET_TO_DEFAULTS", "Reset to defaults"),
                            ("MANDATORY_NOTIFICATION_SENT", "Mandatory notification sent"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="notifications.notificationcategory",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="notifications.notificationchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "-timestamp"],
                        name="notificatio_user_id_a56be2_idx",
                    ),
                    models.Index(fields=["-timestamp"], name="notificatio_timesta_0a6e56_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuietHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiet_hours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "enabled"], name="notificatio_user_id_ed3a13_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="notifications.notificationcategory",
                    ),
                ),
                (
                    "notification_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="notifications.notificationchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__email", "notification_category__display_order"],
                "indexes": [
                    models.Index(
                        fields=["user", "notification_category"],
                        name="notificatio_user_id_a38728_idx",
                    ),
                    models.Index(fields=["user", "enabled"], name="notificatio_user_id_586b43_idx"),
                ],
                "unique_together": {("user", "notification_category", "notification_channel")},
            },
        ),
    ]
